import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _supported = ['en', 'ar', 'bn'];

const _translations = <String, Map<String, String>>{
  // ─────────────────────────────────────────────────────────── ENGLISH ──
  'en': {
    // Global / nav
    'app_name':        'Sunnah Grandeur',
    'tagline':         'Living the Prophetic Way',
    'home':            'Home',
    'media':           'Media',
    'store':           'Store',
    'profile':         'Profile',
    'language':        'Language',
    'location':        'Location',
    'settings':        'Settings',
    'apply':           'Apply',
    'continue':        'Continue',
    'skip':            'Skip for now',
    'save':            'Save',
    'cancel':          'Cancel',
    'done':            'Done',
    'search':          'Search',
    'back':            'Back',
    'close':           'Close',
    'loading':         'Loading...',
    'error':           'Something went wrong',
    'retry':           'Retry',
    'in':              'in',
    // Language onboarding
    'select_lang':     'Choose Your Language',
    'select_lang_sub': 'Select your preferred language\nto begin your journey',
    'continue_with':   'Continue with',
    // Home screen
    'daily_inspiration': 'Daily Inspiration',
    'hadith':            'Hadith',
    'sawm':              'Sawm',
    'active':            'Active',
    'quick_access':      'Quick Access',
    'next_prayer':       'Next Prayer',
    'namaz_schedule':    'Namaz Schedule',
    'five_prayer_times': '5 prayer times',
    'forbidden_times':   'Forbidden Times',
    'makrooh_windows':   'Makrooh windows',
    'qibla_finder':      'Qibla Finder',
    'live_compass':      'Live Compass',
    'tasbeeh':           'Tasbeeh',
    'digital_dhikr':     'Digital dhikr',
    'masjid_finder':     'Masjid Finder',
    'mosques_nearby':    '3 mosques nearby · Nearest 0.4 mi',
    'i_fasted_today':    'I fasted today',
    'sehri':             'Sehri',
    'iftar':             'Iftar',
    'today':             'Today',
    'added_today':       'Added today',
    'calculation_mwl':   'Calculation: MWL',
    // Prayer times
    'prayer_times':    'Prayer Times',
    'fajr':            'Fajr',
    'dhuhr':           'Dhuhr',
    'asr':             'Asr',
    'maghrib':         'Maghrib',
    'isha':            'Isha',
    'sunrise':         'Sunrise',
    'sunset':          'Sunset',
    'all_prayers':     'All Prayer Times',
    // Profile screen
    'your_islamic_journey': 'Your Islamic Journey',
    'preferences':          'Preferences',
    'community':            'Community',
    'account_identity':     'Account & Identity',
    'account_sub':          'Name · Email · Password',
    'notifications':        'Notifications',
    'notifications_sub':    'Prayer alerts · Reminders',
    'appearance':           'Appearance',
    'dark_mode':            'Dark Mode',
    'light_mode':           'Light Mode',
    'prayer_method':        'Prayer Method',
    'prayer_method_sub':    'ISNA · Shafi\'i',
    'invite_friends':       'Invite Friends',
    'invite_friends_sub':   'Share Sunnah Grandeur',
    'rate_app':             'Rate the App',
    'rate_app_sub':         'Spread the khair',
    'sign_out':             'Sign Out',
    'pro_member':           'Pro Member',
    'prayers_stat':         'Prayers',
    'streak':               'Streak',
    'days_fasted':          'Days Fasted',
    'tasbeeh_stat':         'Tasbeeh',
    'guest_user':           'Guest User',
    'anonymous_account':    'Anonymous Account',
    'verified_member':      'Verified Member',
    'language_english':     'English',
    'location_default':     'Set Location',
    // Media screen
    'islamic_content_library': 'Islamic Content Library',
    'choose_section':          'Choose a Section',
    'islamic_videos':          'Islamic Videos',
    'islamic_videos_sub':      'Lectures · Tafseer · Education · Nasheeds',
    'quran':                   'Quran',
    'quran_sub':               'Tilawah · Tajweed · Memorization · Tafseer',
    'ruqyah':                  'Ruqyah',
    'ruqyah_sub':              'Healing Recitations · Protection · Evil Eye',
    'trending_now':            'Trending Now',
    'section_01':              'Section 01',
    'section_02':              'Section 02',
    'section_03':              'Section 03',
    'videos':                  'videos',
    'surahs':                  'surahs',
    'recitations':             'recitations',
    // Store screen
    'islamic_lifestyle':       'Islamic Lifestyle Essentials',
    'featured_products':       'Featured Products',
    'ramadan_exclusive':       'Ramadan Exclusive',
    'free_shipping':           'Free Shipping on £30+',
    'shop_now':                'Shop Now',
    'cat_all':                 'All',
    'cat_books':               'Books',
    'cat_clothing':            'Clothing',
    'cat_prayer':              'Prayer',
    'cat_home':                'Home',
    'cat_jewellery':           'Jewellery',
    // Auth screens
    'welcome_back':            'Welcome Back',
    'login_subtitle':          'Log in to continue your journey',
    'email':                   'Email',
    'password':                'Password',
    'forgot_password':         'Forgot Password?',
    'login':                   'Login',
    'no_account':              "Don't have an account? ",
    'register_now':            'Register Now',
    'fill_fields':             'Please fill all fields',
    'login_failed':            'Login failed. Please check your credentials.',
    'create_account':          'Create Account',
    'register_subtitle':       'Begin your Islamic journey today',
    'name':                    'Full Name',
    'register':                'Register',
    'already_account':         'Already have an account? ',
    'sign_in':                 'Sign In',
    'register_failed':         'Registration failed. Please try again.',
    // Onboarding
    'enable_notifications':    'Enable Notifications',
    'notifications_desc':      'Get prayer time alerts and Islamic reminders',
    'enable_btn':              'Enable',
    'maybe_later':             'Maybe Later',
    'set_location':            'Set Your Location',
    'location_desc':           'For accurate prayer times and Qibla direction',
    'detect_location':         'Detect My Location',
    // Settings
    'interface_language':      'INTERFACE LANGUAGE',
    'select_language':         'Select Language',
    'language_updated':        'Language updated',
    // Prayer tools
    'qibla':                   'Qibla',
    'qibla_sub':               'Direction to Makkah',
    'tasbeeh_counter':         'Tasbeeh Counter',
    'reset':                   'Reset',
    'forbidden_title':         'Forbidden Prayer Times',
    'nearby_masjids':          'Nearby Masjids',
    // Notifications
    'prayer_alerts':           'Prayer Alerts',
    'daily_reminder':          'Daily Reminder',
    'enabled':                 'Enabled',
    'disabled':                'Disabled',
    // Misc
    'share':                   'Share',
    'add_to_cart':             'Add to Cart',
    'checkout':                'Checkout',
    'order_confirmed':         'Order Confirmed',
    'continue_shopping':       'Continue Shopping',
  },

  // ─────────────────────────────────────────────────────────── ARABIC ──
  'ar': {
    // Global / nav
    'app_name':        'سنة الفخامة',
    'tagline':         'العيش على الطريقة النبوية',
    'home':            'الرئيسية',
    'media':           'الوسائط',
    'store':           'المتجر',
    'profile':         'الملف',
    'language':        'اللغة',
    'location':        'الموقع',
    'settings':        'الإعدادات',
    'apply':           'تطبيق',
    'continue':        'متابعة',
    'skip':            'تخطي',
    'save':            'حفظ',
    'cancel':          'إلغاء',
    'done':            'تم',
    'search':          'بحث',
    'back':            'رجوع',
    'close':           'إغلاق',
    'loading':         'جاري التحميل...',
    'error':           'حدث خطأ ما',
    'retry':           'إعادة المحاولة',
    'in':              'خلال',
    // Language onboarding
    'select_lang':     'اختر لغتك',
    'select_lang_sub': 'اختر لغتك المفضلة\nلبدء رحلتك',
    'continue_with':   'متابعة بـ',
    // Home screen
    'daily_inspiration': 'الإلهام اليومي',
    'hadith':            'حديث',
    'sawm':              'الصوم',
    'active':            'نشط',
    'quick_access':      'وصول سريع',
    'next_prayer':       'الصلاة القادمة',
    'namaz_schedule':    'جدول الصلاة',
    'five_prayer_times': '٥ أوقات صلاة',
    'forbidden_times':   'الأوقات المنهي عنها',
    'makrooh_windows':   'أوقات الكراهة',
    'qibla_finder':      'محدد القبلة',
    'live_compass':      'البوصلة الحية',
    'tasbeeh':           'التسبيح',
    'digital_dhikr':     'الذكر الرقمي',
    'masjid_finder':     'البحث عن مسجد',
    'mosques_nearby':    '٣ مساجد قريبة · أقرب ٠٫٤ ميل',
    'i_fasted_today':    'صمت اليوم',
    'sehri':             'سحور',
    'iftar':             'إفطار',
    'today':             'اليوم',
    'added_today':       'أضيف اليوم',
    'calculation_mwl':   'حساب: رابطة العالم الإسلامي',
    // Prayer times
    'prayer_times':    'أوقات الصلاة',
    'fajr':            'الفجر',
    'dhuhr':           'الظهر',
    'asr':             'العصر',
    'maghrib':         'المغرب',
    'isha':            'العشاء',
    'sunrise':         'الشروق',
    'sunset':          'الغروب',
    'all_prayers':     'جميع أوقات الصلاة',
    // Profile screen
    'your_islamic_journey': 'رحلتك الإسلامية',
    'preferences':          'التفضيلات',
    'community':            'المجتمع',
    'account_identity':     'الحساب والهوية',
    'account_sub':          'الاسم · البريد الإلكتروني · كلمة المرور',
    'notifications':        'الإشعارات',
    'notifications_sub':    'تنبيهات الصلاة · التذكيرات',
    'appearance':           'المظهر',
    'dark_mode':            'الوضع الداكن',
    'light_mode':           'الوضع الفاتح',
    'prayer_method':        'طريقة حساب الصلاة',
    'prayer_method_sub':    'رابطة الإسلام الشمالية · شافعي',
    'invite_friends':       'دعوة الأصدقاء',
    'invite_friends_sub':   'شارك سنة الفخامة',
    'rate_app':             'تقييم التطبيق',
    'rate_app_sub':         'انشر الخير',
    'sign_out':             'تسجيل الخروج',
    'pro_member':           'عضو مميز',
    'prayers_stat':         'صلوات',
    'streak':               'تسلسل',
    'days_fasted':          'أيام الصيام',
    'tasbeeh_stat':         'تسبيح',
    'guest_user':           'مستخدم ضيف',
    'anonymous_account':    'حساب مجهول',
    'verified_member':      'عضو موثق',
    'language_english':     'اللغة',
    'location_default':     'تحديد الموقع',
    // Media screen
    'islamic_content_library': 'مكتبة المحتوى الإسلامي',
    'choose_section':          'اختر قسماً',
    'islamic_videos':          'الفيديوهات الإسلامية',
    'islamic_videos_sub':      'المحاضرات · التفسير · التعليم · الأناشيد',
    'quran':                   'القرآن',
    'quran_sub':               'التلاوة · التجويد · الحفظ · التفسير',
    'ruqyah':                  'الرقية',
    'ruqyah_sub':              'تلاوات شفائية · الحماية · العين',
    'trending_now':            'الأكثر انتشاراً',
    'section_01':              'القسم ٠١',
    'section_02':              'القسم ٠٢',
    'section_03':              'القسم ٠٣',
    'videos':                  'فيديو',
    'surahs':                  'سور',
    'recitations':             'تلاوة',
    // Store screen
    'islamic_lifestyle':       'مستلزمات نمط الحياة الإسلامية',
    'featured_products':       'المنتجات المميزة',
    'ramadan_exclusive':       'إصدار رمضاني',
    'free_shipping':           'شحن مجاني عند ٣٠ جنيه+',
    'shop_now':                'تسوق الآن',
    'cat_all':                 'الكل',
    'cat_books':               'الكتب',
    'cat_clothing':            'الملابس',
    'cat_prayer':              'الصلاة',
    'cat_home':                'المنزل',
    'cat_jewellery':           'المجوهرات',
    // Auth screens
    'welcome_back':            'مرحباً بعودتك',
    'login_subtitle':          'سجّل دخولك لمتابعة رحلتك',
    'email':                   'البريد الإلكتروني',
    'password':                'كلمة المرور',
    'forgot_password':         'نسيت كلمة المرور؟',
    'login':                   'تسجيل الدخول',
    'no_account':              'ليس لديك حساب؟ ',
    'register_now':            'سجّل الآن',
    'fill_fields':             'يرجى ملء جميع الحقول',
    'login_failed':            'فشل تسجيل الدخول. يرجى التحقق من بيانات الاعتماد.',
    'create_account':          'إنشاء حساب',
    'register_subtitle':       'ابدأ رحلتك الإسلامية اليوم',
    'name':                    'الاسم الكامل',
    'register':                'تسجيل',
    'already_account':         'لديك حساب بالفعل؟ ',
    'sign_in':                 'تسجيل الدخول',
    'register_failed':         'فشل التسجيل. يرجى المحاولة مرة أخرى.',
    // Onboarding
    'enable_notifications':    'تفعيل الإشعارات',
    'notifications_desc':      'احصل على تنبيهات أوقات الصلاة وتذكيرات إسلامية',
    'enable_btn':              'تفعيل',
    'maybe_later':             'ربما لاحقاً',
    'set_location':            'تحديد موقعك',
    'location_desc':           'لأوقات صلاة دقيقة واتجاه القبلة',
    'detect_location':         'تحديد موقعي',
    // Settings
    'interface_language':      'لغة الواجهة',
    'select_language':         'اختر اللغة',
    'language_updated':        'تم تحديث اللغة',
    // Prayer tools
    'qibla':                   'القبلة',
    'qibla_sub':               'اتجاه مكة المكرمة',
    'tasbeeh_counter':         'عداد التسبيح',
    'reset':                   'إعادة ضبط',
    'forbidden_title':         'أوقات الصلاة المنهي عنها',
    'nearby_masjids':          'المساجد القريبة',
    // Notifications
    'prayer_alerts':           'تنبيهات الصلاة',
    'daily_reminder':          'التذكير اليومي',
    'enabled':                 'مفعّل',
    'disabled':                'معطّل',
    // Misc
    'share':                   'مشاركة',
    'add_to_cart':             'أضف إلى السلة',
    'checkout':                'الدفع',
    'order_confirmed':         'تم تأكيد الطلب',
    'continue_shopping':       'متابعة التسوق',
  },

  // ─────────────────────────────────────────────────────────── BANGLA ──
  'bn': {
    // Global / nav
    'app_name':        'সুন্নাহ গ্র্যান্ডার',
    'tagline':         'নবীজির পথে জীবন যাপন',
    'home':            'হোম',
    'media':           'মিডিয়া',
    'store':           'স্টোর',
    'profile':         'প্রোফাইল',
    'language':        'ভাষা',
    'location':        'অবস্থান',
    'settings':        'সেটিংস',
    'apply':           'প্রয়োগ করুন',
    'continue':        'চালিয়ে যান',
    'skip':            'এখন এড়িয়ে যান',
    'save':            'সংরক্ষণ',
    'cancel':          'বাতিল',
    'done':            'সম্পন্ন',
    'search':          'অনুসন্ধান',
    'back':            'পিছনে',
    'close':           'বন্ধ',
    'loading':         'লোড হচ্ছে...',
    'error':           'কিছু একটা ভুল হয়েছে',
    'retry':           'আবার চেষ্টা করুন',
    'in':              'পরে',
    // Language onboarding
    'select_lang':     'আপনার ভাষা বেছে নিন',
    'select_lang_sub': 'আপনার পছন্দের ভাষা নির্বাচন করুন\nযাত্রা শুরু করতে',
    'continue_with':   'এগিয়ে যান',
    // Home screen
    'daily_inspiration': 'দৈনিক অনুপ্রেরণা',
    'hadith':            'হাদিস',
    'sawm':              'সাওম',
    'active':            'সক্রিয়',
    'quick_access':      'দ্রুত অ্যাক্সেস',
    'next_prayer':       'পরবর্তী নামাজ',
    'namaz_schedule':    'নামাজের সময়সূচি',
    'five_prayer_times': '৫ ওয়াক্ত নামাজ',
    'forbidden_times':   'নিষিদ্ধ সময়',
    'makrooh_windows':   'মাকরুহ সময়',
    'qibla_finder':      'কিবলা নির্ণয়',
    'live_compass':      'লাইভ কম্পাস',
    'tasbeeh':           'তাসবিহ',
    'digital_dhikr':     'ডিজিটাল জিকর',
    'masjid_finder':     'মসজিদ খুঁজুন',
    'mosques_nearby':    '৩টি কাছের মসজিদ · নিকটতম ০.৪ মাইল',
    'i_fasted_today':    'আজ রোজা রেখেছি',
    'sehri':             'সেহরি',
    'iftar':             'ইফতার',
    'today':             'আজ',
    'added_today':       'আজ যোগ হয়েছে',
    'calculation_mwl':   'হিসাব: MWL',
    // Prayer times
    'prayer_times':    'নামাজের সময়',
    'fajr':            'ফজর',
    'dhuhr':           'যোহর',
    'asr':             'আসর',
    'maghrib':         'মাগরিব',
    'isha':            'এশা',
    'sunrise':         'সূর্যোদয়',
    'sunset':          'সূর্যাস্ত',
    'all_prayers':     'সব নামাজের সময়',
    // Profile screen
    'your_islamic_journey': 'আপনার ইসলামি যাত্রা',
    'preferences':          'পছন্দসমূহ',
    'community':            'সম্প্রদায়',
    'account_identity':     'অ্যাকাউন্ট ও পরিচয়',
    'account_sub':          'নাম · ইমেইল · পাসওয়ার্ড',
    'notifications':        'বিজ্ঞপ্তি',
    'notifications_sub':    'নামাজের সতর্কতা · রিমাইন্ডার',
    'appearance':           'উপস্থিতি',
    'dark_mode':            'ডার্ক মোড',
    'light_mode':           'লাইট মোড',
    'prayer_method':        'নামাজ হিসাবের পদ্ধতি',
    'prayer_method_sub':    'ISNA · শাফেয়ি',
    'invite_friends':       'বন্ধুদের আমন্ত্রণ জানান',
    'invite_friends_sub':   'সুন্নাহ গ্র্যান্ডার শেয়ার করুন',
    'rate_app':             'অ্যাপ রেটিং দিন',
    'rate_app_sub':         'কল্যাণ ছড়িয়ে দিন',
    'sign_out':             'সাইন আউট',
    'pro_member':           'প্রো সদস্য',
    'prayers_stat':         'নামাজ',
    'streak':               'ধারাবাহিকতা',
    'days_fasted':          'রোজার দিন',
    'tasbeeh_stat':         'তাসবিহ',
    'guest_user':           'অতিথি ব্যবহারকারী',
    'anonymous_account':    'বেনামী অ্যাকাউন্ট',
    'verified_member':      'যাচাইকৃত সদস্য',
    'language_english':     'ভাষা',
    'location_default':     'অবস্থান নির্ধারণ করুন',
    // Media screen
    'islamic_content_library': 'ইসলামিক কন্টেন্ট লাইব্রেরি',
    'choose_section':          'একটি বিভাগ বেছে নিন',
    'islamic_videos':          'ইসলামিক ভিডিও',
    'islamic_videos_sub':      'বক্তৃতা · তাফসির · শিক্ষা · নাশিদ',
    'quran':                   'কুরআন',
    'quran_sub':               'তিলাওয়াত · তাজওয়িদ · হিফজ · তাফসির',
    'ruqyah':                  'রুকইয়াহ',
    'ruqyah_sub':              'নিরাময় তিলাওয়াত · সুরক্ষা · নজর',
    'trending_now':            'এখন ট্রেন্ডিং',
    'section_01':              'বিভাগ ০১',
    'section_02':              'বিভাগ ০২',
    'section_03':              'বিভাগ ০৩',
    'videos':                  'ভিডিও',
    'surahs':                  'সূরা',
    'recitations':             'তিলাওয়াত',
    // Store screen
    'islamic_lifestyle':       'ইসলামিক জীবনযাত্রার পণ্য',
    'featured_products':       'বৈশিষ্ট্যযুক্ত পণ্য',
    'ramadan_exclusive':       'রমজান এক্সক্লুসিভ',
    'free_shipping':           '£৩০+ এ বিনামূল্যে শিপিং',
    'shop_now':                'এখন কিনুন',
    'cat_all':                 'সব',
    'cat_books':               'বই',
    'cat_clothing':            'পোশাক',
    'cat_prayer':              'নামাজ',
    'cat_home':                'গৃহ',
    'cat_jewellery':           'গহনা',
    // Auth screens
    'welcome_back':            'আবার স্বাগতম',
    'login_subtitle':          'আপনার যাত্রা চালিয়ে যেতে লগ ইন করুন',
    'email':                   'ইমেইল',
    'password':                'পাসওয়ার্ড',
    'forgot_password':         'পাসওয়ার্ড ভুলে গেছেন?',
    'login':                   'লগ ইন',
    'no_account':              'অ্যাকাউন্ট নেই? ',
    'register_now':            'এখনই নিবন্ধন করুন',
    'fill_fields':             'সকল ঘর পূরণ করুন',
    'login_failed':            'লগইন ব্যর্থ হয়েছে। আপনার তথ্য যাচাই করুন।',
    'create_account':          'অ্যাকাউন্ট তৈরি করুন',
    'register_subtitle':       'আজই আপনার ইসলামিক যাত্রা শুরু করুন',
    'name':                    'পূর্ণ নাম',
    'register':                'নিবন্ধন করুন',
    'already_account':         'ইতিমধ্যে অ্যাকাউন্ট আছে? ',
    'sign_in':                 'সাইন ইন',
    'register_failed':         'নিবন্ধন ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    // Onboarding
    'enable_notifications':    'বিজ্ঞপ্তি চালু করুন',
    'notifications_desc':      'নামাজের সময়ের সতর্কতা ও ইসলামিক রিমাইন্ডার পান',
    'enable_btn':              'চালু করুন',
    'maybe_later':             'পরে হয়তো',
    'set_location':            'আপনার অবস্থান নির্ধারণ করুন',
    'location_desc':           'সঠিক নামাজের সময় ও কিবলার দিকের জন্য',
    'detect_location':         'আমার অবস্থান শনাক্ত করুন',
    // Settings
    'interface_language':      'ইন্টারফেস ভাষা',
    'select_language':         'ভাষা নির্বাচন করুন',
    'language_updated':        'ভাষা আপডেট হয়েছে',
    // Prayer tools
    'qibla':                   'কিবলা',
    'qibla_sub':               'মক্কার দিক',
    'tasbeeh_counter':         'তাসবিহ কাউন্টার',
    'reset':                   'রিসেট',
    'forbidden_title':         'নিষিদ্ধ নামাজের সময়',
    'nearby_masjids':          'কাছের মসজিদ',
    // Notifications
    'prayer_alerts':           'নামাজের সতর্কতা',
    'daily_reminder':          'দৈনিক রিমাইন্ডার',
    'enabled':                 'সক্রিয়',
    'disabled':                'নিষ্ক্রিয়',
    // Misc
    'share':                   'শেয়ার',
    'add_to_cart':             'কার্টে যোগ করুন',
    'checkout':                'চেকআউট',
    'order_confirmed':         'অর্ডার নিশ্চিত হয়েছে',
    'continue_shopping':       'কেনাকাটা চালিয়ে যান',
  },
};

class LanguageProvider extends ChangeNotifier {
  static const _key = 'selected_locale';

  String _langCode = 'en';

  String get langCode => _langCode;
  Locale get locale   => Locale(_langCode);
  bool   get isRtl    => _langCode == 'ar';

  LanguageProvider() {
    _loadSaved();
  }

  Future<void> _loadSaved() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString(_key) ?? 'en';
    _langCode = _supported.contains(saved) ? saved : 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String code) async {
    if (!_supported.contains(code)) return;
    if (_langCode == code) return;
    _langCode = code;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_key, code);
    notifyListeners();
  }

  String tr(String key) {
    return _translations[_langCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }
}
