import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _supported = ['en', 'ar', 'bn'];

const _translations = <String, Map<String, String>>{
  // ─────────────────────────────────────────────────────────── ENGLISH ──
  'en': {
    // Global / nav
    'app_name':        'Sunnah Grandeur',
    'tagline':         'Living the Prophetic Way',
    'muslim_productivity_tag': 'Muslim Productivity, by Sunnah Grandeur',
    'home':            'Home',
    'media':           'Media',
    'store':           'Store',
    'profile':         'Profile',
    'language':        'Language',
    'location':        'Location',
    'settings':        'Settings',
    'apply':           'Apply',
    'continue':        'Continue',
    'skip':            'Skip for now',
    'save':            'Save',
    'cancel':          'Cancel',
    'done':            'Done',
    'search':          'Search',
    'back':            'Back',
    'close':           'Close',
    'loading':         'Loading...',
    'error':           'Something went wrong',
    'retry':           'Retry',
    'in':              'in',
    // Language onboarding
    'select_lang':     'Choose Your Language',
    'select_lang_sub': 'Select your preferred language\nto begin your journey',
    'continue_with':   'Continue with',
    // Home screen
    'daily_inspiration': 'Daily Inspiration',
    'hadith':            'Hadith',
    'sawm':              'Sawm',
    'active':            'Active',
    'quick_access':      'Quick Access',
    'next_prayer':       'Next Prayer',
    'namaz_schedule':    'Namaz Schedule',
    'five_prayer_times': '5 prayer times',
    'forbidden_times':   'Forbidden Times',
    'makrooh_windows':   'Makrooh windows',
    'qibla_finder':      'Qibla Finder',
    'live_compass':      'Live Compass',
    'tasbeeh':           'Tasbeeh',
    'digital_dhikr':     'Digital dhikr',
    'masjid_finder':     'Masjid Finder',
    'mosques_nearby':    'Find mosques near you',
    'zakat_calculator':  'Zakat Calculator',
    'calculate_zakat_due': 'Calculate what you owe',
    'hijri_calendar':    'Hijri Calendar',
    'islamic_lunar_dates': 'Islamic lunar dates',
    'i_fasted_today':    'I fasted today',
    'sehri':             'Sehri',
    'iftar':             'Iftar',
    'today':             'Today',
    'added_today':       'Added today',
    'calculation':       'Calculation',
    // Prayer times
    'prayer_times':    'Prayer Times',
    'fajr':            'Fajr',
    'dhuhr':           'Dhuhr',
    'asr':             'Asr',
    'maghrib':         'Maghrib',
    'isha':            'Isha',
    'sunrise':         'Sunrise',
    'sunset':          'Sunset',
    'all_prayers':     'All Prayer Times',
    // Profile screen
    'your_islamic_journey': 'Your Islamic Journey',
    'preferences':          'Preferences',
    'community':            'Community',
    'account_identity':     'Account & Identity',
    'account_sub':          'Name · Email · Password',
    'notifications':        'Notifications',
    'notifications_sub':    'Prayer alerts · Reminders',
    'appearance':           'Appearance',
    'dark_mode':            'Dark Mode',
    'light_mode':           'Light Mode',
    'prayer_method':        'Prayer Method',
    'prayer_method_sub':    'ISNA · Shafi\'i',
    'invite_friends':       'Invite Friends',
    'invite_friends_sub':   'Share Sunnah Grandeur',
    'rate_app':             'Rate the App',
    'rate_app_sub':         'Spread the khair',
    'support_us':           'Support Us',
    'support_us_sub':       'Shop with us or share the app',
    'sign_out':             'Sign Out',
    'pro_member':           'Pro Member',
    'prayers_stat':         'Prayers',
    'streak':               'Streak',
    'days_fasted':          'Days Fasted',
    'tasbeeh_stat':         'Tasbeeh',
    'guest_user':           'Guest User',
    'anonymous_account':    'Anonymous Account',
    'verified_member':      'Verified Member',
    'language_english':     'English',
    'location_default':     'Set Location',
    // Media screen
    'islamic_content_library': 'Islamic Content Library',
    'choose_section':          'Choose a Section',
    'islamic_videos':          'Islamic Videos',
    'islamic_videos_sub':      'Lectures · Tafseer · Education · Nasheeds',
    'quran':                   'Quran',
    'quran_sub':               'Tilawah · Tajweed · Memorization · Tafseer',
    'ruqyah':                  'Ruqyah',
    'ruqyah_sub':              'Healing Recitations · Protection · Evil Eye',
    'trending_now':            'Trending Now',
    'section_01':              'Section 01',
    'section_02':              'Section 02',
    'section_03':              'Section 03',
    'videos':                  'videos',
    'surahs':                  'surahs',
    'recitations':             'recitations',
    // Store screen
    'islamic_lifestyle':       'Islamic Lifestyle Essentials',
    'featured_products':       'Featured Products',
    'ramadan_exclusive':       'Ramadan Exclusive',
    'free_shipping':           'Free Shipping on £30+',
    'shop_now':                'Shop Now',
    'cat_all':                 'All',
    'cat_books':               'Books',
    'cat_clothing':            'Clothing',
    'cat_prayer':              'Prayer',
    'cat_home':                'Home',
    'cat_jewellery':           'Jewellery',
    // Auth screens
    'welcome_back':            'Welcome Back',
    'login_subtitle':          'Log in to continue your journey',
    'email':                   'Email',
    'password':                'Password',
    'forgot_password':         'Forgot Password?',
    'login':                   'Login',
    'no_account':              "Don't have an account? ",
    'register_now':            'Register Now',
    'fill_fields':             'Please fill all fields',
    'login_failed':            'Login failed. Please check your credentials.',
    'create_account':          'Create Account',
    'register_subtitle':       'Begin your Islamic journey today',
    'name':                    'Full Name',
    'register':                'Register',
    'already_account':         'Already have an account? ',
    'sign_in':                 'Sign In',
    'register_failed':         'Registration failed. Please try again.',
    'email_required':          'Email is required',
    'email_invalid':           'Enter a valid email',
    'password_required':       'Password is required',
    'save_progress':           'Save Your Progress',
    'guest_register_sub':      'Create an account to sync your favorites, orders & settings.',
    'join_community_sub':      'Join the community. Takes less than a minute.',
    'guest_session_notice':    'Your guest session will be preserved when you upgrade.',
    'continue_with_google':    'Continue with Google',
    'or_create_with_email':    'or create with email',
    'name_required':           'Name is required',
    'name_too_short':          'Name is too short',
    'min_6_chars':             'Minimum 6 characters',
    'save_upgrade_account':    'Save & Upgrade Account',
    'enter_email_prompt':      'Please enter your email',
    'reset_password_title':    'Reset Password',
    'reset_password_sub':      'Enter your email to receive a password reset link',
    'send_reset_link':         'Send Reset Link',
    'reset_link_sent':         'Password reset link sent to your email',
    'reset_link_failed':       'Failed to send reset link. Please try again.',
    // Zakat calculator
    'zakat_calc_tag':          'CALCULATE YOUR ANNUAL ZAKAT',
    'about_zakat':             'About Zakat',
    'about_zakat_body':        'Zakat is due once your total zakatable wealth has met or exceeded the Nisab '
        '(the value of 85g of gold) and has been held for one lunar year. Enter your '
        'assets below to see what you owe.',
    'your_zakatable_assets':   'YOUR ZAKATABLE ASSETS',
    'cash_savings':            'Cash & Savings',
    'cash_savings_hint':       'Bank balances, cash on hand',
    'gold_owned':              'Gold You Own (grams)',
    'gold_owned_hint':         'Total weight of gold owned',
    'silver_owned':            'Silver You Own (grams)',
    'silver_owned_hint':       'Total weight of silver owned',
    'business_assets':         'Business Assets / Inventory',
    'business_assets_hint':    'Value of stock-in-trade & receivables',
    'other_investments':       'Other Investments',
    'other_investments_hint':  'Stocks, crypto, other zakatable holdings',
    'current_market_prices':   'CURRENT MARKET PRICES',
    'live_price_refresh':      'Live price — tap to refresh',
    'tap_fetch_price':         'Tap to fetch today\'s price',
    'gold_price_gram':         'Gold Price (per gram)',
    'gold_price_gram_hint':    'Used for gold value & Nisab threshold',
    'silver_price_gram':       'Silver Price (per gram)',
    'silver_price_gram_hint':  'Used for silver value',
    'zakat_result':            'RESULT',
    'total_zakatable_wealth':  'TOTAL ZAKATABLE WEALTH',
    'gold_silver_value':       'Gold + Silver value',
    'nisab_threshold':         'NISAB THRESHOLD (85g GOLD)',
    'zakat_due_this_year':     'Zakat is due this year',
    'zakat_due_pct':           'ZAKAT DUE (2.5%)',
    'below_nisab_notice':      'Your total wealth is below the Nisab threshold — no Zakat is due this year.',
    // Onboarding
    'enable_notifications':    'Enable Notifications',
    'notifications_desc':      'Get prayer time alerts and Islamic reminders',
    'enable_btn':              'Enable',
    'maybe_later':             'Maybe Later',
    'set_location':            'Set Your Location',
    'location_desc':           'For accurate prayer times and Qibla direction',
    'detect_location':         'Detect My Location',
    // Settings
    'interface_language':      'INTERFACE LANGUAGE',
    'select_language':         'Select Language',
    'language_updated':        'Language updated',
    // Prayer tools
    'qibla':                   'Qibla',
    'qibla_sub':               'Direction to Makkah',
    'tasbeeh_counter':         'Tasbeeh Counter',
    'reset':                   'Reset',
    'forbidden_title':         'Forbidden Prayer Times',
    'nearby_masjids':          'Nearby Masjids',
    // Notifications
    'prayer_alerts':           'Prayer Alerts',
    'daily_reminder':          'Daily Reminder',
    'enabled':                 'Enabled',
    'disabled':                'Disabled',
    // Misc
    'share':                   'Share',
    'add_to_cart':             'Add to Cart',
    'checkout':                'Checkout',
    'order_confirmed':         'Order Confirmed',
    'continue_shopping':       'Continue Shopping',
    // Cart / Checkout screens
    'cart':                    'Cart',
    'your_cart':               'Your Cart',
    'cart_empty_title':        'Your cart is empty',
    'cart_empty_sub':          'Add items from the shop to get started.',
    'cart_review_sub':         'Review your selections before completing your purchase.',
    'order_summary':           'Order Summary',
    'subtotal':                'Subtotal',
    'estimated_tax':           'Estimated Tax',
    'shipping':                'Shipping',
    'free_shipping_usa':       'Free — Across the USA',
    'total':                   'Total',
    'proceed_checkout':        'PROCEED TO CHECKOUT',
    'secure_checkout':         'Secure Encrypted Checkout',
    'secure_checkout_title':   'Secure Checkout',
    'contact_information':     'Contact Information',
    'full_name':               'Full Name',
    'email_address':           'Email Address',
    'phone_number':            'Phone Number',
    'phone_required':          'Phone number is required',
    'shipping_address':        'Shipping Address',
    'street_address':          'Street Address',
    'address_required':        'Address is required',
    'city':                    'City',
    'city_required':           'City is required',
    'state_label':             'State',
    'zip_postal_code':         'ZIP / Postal Code',
    'zip_required':            'ZIP required',
    'payment_method':          'Payment Method',
    'cash_on_delivery':        'Cash on Delivery',
    'country_label':           'Country',
    'free_shipping_included':  'Free Shipping Included',
    'powered_by_stripe':       'Powered by Stripe',
    'place_order_cod':         'PLACE ORDER — PAY ON DELIVERY',
    'complete_order':          'COMPLETE ORDER',
    'subtotal_plus':           'Subtotal +',
    'tax_suffix':              'Tax',
    'ssl_encryption':          '256-bit SSL Encryption',
    'your_items':              'Your Items',
    'visit_store':             'Visit the Sunnah Grandeur Store',
    'limited_time_deal':       'Limited time deal',
    'buy_new':                 'Buy New',
    'free_shipping_prefix':    'FREE ',
    'free_shipping_line':      'shipping on every purchase',
    'free_delivery_usa':       'Free Delivery Across the USA',
    'currently_unavailable':   'Currently Unavailable',
    'in_stock':                'In Stock',
    'quantity_label':          'Quantity:',
    'add_to_cart_caps':        'ADD TO CART',
    'buy_now_caps':            'BUY NOW',
    'gift_wrap_prefix':        'Add premium gift wrapping for ',
    'delivery_support':        'DELIVERY & SUPPORT',
    'select_to_learn_more':    'Select to learn more',
    'ships_from':              'Ships from',
    'out_of_stock_caps':       'OUT OF STOCK',
    'free_delivery':           'Free Delivery',
    'across_usa':              'Across the USA',
    'returns_30day':           '30-day Easy',
    'returns':                 'Returns',
    'customer':                'Customer',
    'support':                 'Support',
    'browse':                  'BROWSE',
    'no_products_category':    'No products in this category yet.',
    'view_all_products':       'View all products',
    'categories_caps':         'CATEGORIES',
    // Quran / Ruqyah / video screens
    'surahs_114':              '114 Surahs',
    'ayahs':                   'ayahs',
    'surah':                   'Surah',
    'ayah':                    'Ayah',
    'quran_tab_sub':           'Tilawah · Tajweed · Memorization',
    'read_tab':                'Read',
    'watch_tab':               'Watch',
    'continue_reading':        'Continue Reading',
    'all_recitations':         'All Recitations',
    'no_recitations_available': 'No recitations available',
    'pull_refresh_hint':       'Pull down to refresh or check your connection.',
    'featured_tilawah':        'Featured Tilawah',
    'views':                   'views',
    'ruqyah_tab_sub':          'Healing · Protection · Evil Eye',
    'healing_through_quran':   'Healing through the Quran',
    'ruqyah_info_body':        'Listen in a quiet place. Recitations are based on authentic Sunnah for healing and protection.',
    'featured_caps':           'FEATURED',
    'listens':                 'listens',
    'curated_content_prefix':  'A carefully curated piece of Islamic content from ',
    'curated_content_suffix':  '. Watch in-app for the full experience.',
    'video_unavailable':       'Video unavailable',
    'video_unavailable_body':  'This video may be restricted or unavailable.',
    'curated_youtube_feed':    'Curated YouTube Feed',
    'no_videos_yet':           'No videos yet',
    'videos_will_appear':      'Videos will appear here once added.',
    // Hijri calendar
    'islamic_lunar_calendar_caps': 'ISLAMIC LUNAR CALENDAR',
    'ramadan_mubarak':         'Ramadan Mubarak',
    'ah_suffix':               'AH',
    'eid':                     'Eid',
    'ramadan':                 'Ramadan',
    // Forbidden times
    'makrooh_prayer_windows_caps': 'MAKROOH PRAYER WINDOWS',
    'loading_prayer_times':    'Loading prayer times…',
    'prayer_times_unavailable': 'Prayer times unavailable.',
    'sunrise_window':          'Sunrise Window',
    'after_fajr_avoid':        'After Fajr · avoid prayer',
    'zawal_solar_noon':        'Zawal · Solar Noon',
    'before_dhuhr_begins':     'Before Dhuhr begins',
    'sunset_window':           'Sunset Window',
    'before_maghrib_avoid':    'Before Maghrib · avoid prayer',
    'min_suffix':              'min',
    'about_makrooh_times':     'About Makrooh Times',
    'makrooh_info_body':       'Praying during these windows is disliked (makrooh) in Islamic jurisprudence. '
        'These times are based on your current location and today\'s prayer schedule.',
    'todays_windows_caps':     "TODAY'S WINDOWS",
    'upcoming':                'Upcoming',
    'to_prefix':               'to',
    'duration_prefix':         'Duration:',
    'scholarly_reference_caps': 'SCHOLARLY REFERENCE',
    'window_prefix':           'WINDOW',
    'passed_today':            'Passed today',
    // Masjid Finder
    'could_not_open_navigation': 'Could not open navigation.',
    'masjid_finder_coming_soon': 'Masjid Finder — Coming Soon',
    'masjid_coming_soon_body': 'Nearby mosque search is being set up and will be available shortly.',
    'search_mosques_hint':     'Search mosques, city…',
    'searching_mosques':       'Searching mosques…',
    'no_mosques_found':        'No mosques found',
    'mosque_singular_nearby':  'mosque nearby',
    'mosques_plural_nearby':   'mosques nearby',
    'sorted_by_distance':      'Sorted by distance',
    'finding_nearby_mosques':  'Finding nearby mosques…',
    'no_mosques_found_nearby': 'No mosques found nearby',
    'try_different_area':      'Try searching a different area or city',
    'open_status':             'Open',
    'closed_status':           'Closed',
    'address_label':           'Address',
    'distance_label':          'Distance',
    'status_label':            'Status',
    'unknown_label':           'Unknown',
    'open_now_label':          'Open now',
    'get_directions':          'Get Directions',
    // Adhan settings
    'adhan_sound_coming_soon': "This Adhan sound isn't available yet — coming soon.",
    'adhan_alarms_activated':  'Adhan alarms activated.',
    'prayer_alarms':           'Prayer Alarms',
    'adhan_sound':             'Adhan Sound',
    'volume_label':            'Volume',
    'calculation_method':      'Calculation Method',
    'madhab_school':           'Madhab / School',
    'additional_options':      'Additional Options',
    'activate_adhan_alarms':   'Activate Adhan Alarms',
    'adhan_settings_title':    'Adhan Settings',
    'prayer_alarms_preferences_sub': 'Prayer alarms & preferences',
    'on_label':                'ON',
    'off_label':               'OFF',
    'five_daily_prayers':      '5 Daily Prayers',
    'adhan_alarms_label':      'Adhan Alarms',
    'adhan_ring_each_prayer':  'Adhan will ring at each prayer time',
    'tap_enable_adhan':        'Tap to enable Adhan notifications',
    'alarm_enabled':           'Alarm enabled',
    'alarm_disabled':          'Alarm disabled',
    'later_asr_time':          'Later Asr time',
    'earlier_asr_time':        'Earlier Asr time',
    'vibration_label':         'Vibration',
    'vibrate_device_sub':      'Vibrate device when alarm fires',
    'pre_prayer_reminder':     'Pre-Prayer Reminder',
    'pre_prayer_reminder_sub': 'Notification 10 minutes before each prayer',
    // Support Us / Location / Prayer Method / Appearance / Account / Invite / Rate
    'help_us_grow_caps':       'HELP US GROW',
    'support_prefix':          'Support ',
    'support_body':            'Every purchase from our shop and every friend you tell '
        'about the app directly supports our mission to build '
        'thoughtful tools for the Muslim community.',
    'shop_with_us':            'Shop With Us',
    'shop_with_us_sub':        'Every order funds the products we build next.',
    'share_the_app':           'Share the App',
    'share_the_app_sub':       'Tell a friend or family member about us.',
    'share_message_prefix':    'I use ',
    'share_message_suffix':    ' for prayer times, Qibla, and daily reminders — check it out!',
    'browse_the_shop':         'Browse the Shop',
    'location_updated':        'Location updated',
    'location_set_to_prefix':  'Location set to ',
    'prayer_time_calibration_caps': 'PRAYER TIME CALIBRATION',
    'no_location_set':         'No location set',
    'using_london_fallback':   'Using London fallback',
    'active_label':            'Active',
    'default_label':           'Default',
    'gps_caps':                'GPS',
    'use_current_location':    'Use Current Location',
    'detects_city_via_gps':    'Detects your city via GPS',
    'search_city_caps':        'Search City',
    'search_for_city_hint':    'Search for a city...',
    'popular_cities_caps':     'POPULAR CITIES',
    'prayer_method_saved':     'Prayer method saved.',
    'calculation_madhab_caps': 'CALCULATION & MADHAB',
    'current_prefix':          'Current: ',
    'affects_asr_twilight':    'Affects Asr timing and twilight calculations for your region.',
    'asr_madhab_caps':         'Asr Madhab',
    'earlier_asr':             'Earlier Asr',
    'later_asr':               'Later Asr',
    'save_prayer_method':      'Save Prayer Method',
    'text_size_small':         'Small',
    'text_size_default':       'Default',
    'text_size_large':         'Large',
    'text_size_extra_large':   'Extra Large',
    'theme_display_caps':      'THEME & DISPLAY',
    'theme_mode_caps':         'Theme Mode',
    'use_system_default':      'Use System Default',
    'match_device_appearance': 'Match device appearance',
    'text_size_caps':          'Text Size',
    'profile_updated_success': 'Profile updated successfully',
    'profile_update_failed':   'Failed to update profile',
    'change_password':         'Change Password',
    'send_reset_link_to_prefix': 'Send a password reset link to ',
    'send_link':               'Send Link',
    'reset_link_sent_to_prefix': 'Reset link sent to ',
    'failed_send_reset_link':  'Failed to send reset link',
    'personal_information_caps': 'PERSONAL INFORMATION',
    'guest_label':             'Guest',
    'personal_details_caps':   'Personal Details',
    'security_caps':           'Security',
    'no_email_on_account':     'No email on this account',
    'danger_zone_caps':        'Danger Zone',
    'delete_account':          'Delete Account',
    'delete_account_confirm_body': 'Are you sure you want to permanently delete your account? This action cannot be undone.',
    'delete':                  'Delete',
    'share_msg_body':          'Join me on Sunnah Grandeur — your Islamic lifestyle companion!',
    'could_not_open_app':      'Could not open that app.',
    'share_sunnah_grandeur_caps': 'SHARE SUNNAH GRANDEUR',
    'spread_the_khair':        'Spread the Khair',
    'spread_khair_body':       'Share Sunnah Grandeur with friends and family. Every good deed starts with a reminder.',
    'your_invite_link_caps':   'Your Invite Link',
    'link_copied':             'Link copied!',
    'share_via_caps':          'Share Via',
    'sunnah_grandeur_app_label': 'Sunnah Grandeur App',
    'share_app_link':          'Share App Link',
    'tap_star_first':          'Tap a star to choose a rating first.',
    'could_not_submit_feedback': 'Could not submit feedback',
    'spread_the_khair_caps':   'SPREAD THE KHAIR',
    'enjoying_the_app':        'Enjoying the App?',
    'rating_helps_discover':   'Your rating helps other Muslims discover Sunnah Grandeur. It takes just 10 seconds.',
    'rate_app_hint':           'What do you love most about Sunnah Grandeur? (optional)',
    'feedback_sent':           'Feedback Sent',
    'submit_feedback':         'Submit Feedback',
    'jazakallah_khair':        'JazakAllah Khair for the feedback 🤍',
    'feedback_goes_to_team':   'Your feedback goes straight to our team.',
  },

  // ─────────────────────────────────────────────────────────── ARABIC ──
  'ar': {
    // Global / nav
    'app_name':        'سنة الفخامة',
    'tagline':         'العيش على الطريقة النبوية',
    'muslim_productivity_tag': 'إنتاجية المسلم، من سنة الفخامة',
    'home':            'الرئيسية',
    'media':           'الوسائط',
    'store':           'المتجر',
    'profile':         'الملف',
    'language':        'اللغة',
    'location':        'الموقع',
    'settings':        'الإعدادات',
    'apply':           'تطبيق',
    'continue':        'متابعة',
    'skip':            'تخطي',
    'save':            'حفظ',
    'cancel':          'إلغاء',
    'done':            'تم',
    'search':          'بحث',
    'back':            'رجوع',
    'close':           'إغلاق',
    'loading':         'جاري التحميل...',
    'error':           'حدث خطأ ما',
    'retry':           'إعادة المحاولة',
    'in':              'خلال',
    // Language onboarding
    'select_lang':     'اختر لغتك',
    'select_lang_sub': 'اختر لغتك المفضلة\nلبدء رحلتك',
    'continue_with':   'متابعة بـ',
    // Home screen
    'daily_inspiration': 'الإلهام اليومي',
    'hadith':            'حديث',
    'sawm':              'الصوم',
    'active':            'نشط',
    'quick_access':      'وصول سريع',
    'next_prayer':       'الصلاة القادمة',
    'namaz_schedule':    'جدول الصلاة',
    'five_prayer_times': '٥ أوقات صلاة',
    'forbidden_times':   'الأوقات المنهي عنها',
    'makrooh_windows':   'أوقات الكراهة',
    'qibla_finder':      'محدد القبلة',
    'live_compass':      'البوصلة الحية',
    'tasbeeh':           'التسبيح',
    'digital_dhikr':     'الذكر الرقمي',
    'masjid_finder':     'البحث عن مسجد',
    'mosques_nearby':    'ابحث عن المساجد القريبة منك',
    'zakat_calculator':  'حاسبة الزكاة',
    'calculate_zakat_due': 'احسب ما يجب عليك',
    'hijri_calendar':    'التقويم الهجري',
    'islamic_lunar_dates': 'التواريخ الهجرية',
    'i_fasted_today':    'صمت اليوم',
    'sehri':             'سحور',
    'iftar':             'إفطار',
    'today':             'اليوم',
    'added_today':       'أضيف اليوم',
    'calculation':       'الحساب',
    // Prayer times
    'prayer_times':    'أوقات الصلاة',
    'fajr':            'الفجر',
    'dhuhr':           'الظهر',
    'asr':             'العصر',
    'maghrib':         'المغرب',
    'isha':            'العشاء',
    'sunrise':         'الشروق',
    'sunset':          'الغروب',
    'all_prayers':     'جميع أوقات الصلاة',
    // Profile screen
    'your_islamic_journey': 'رحلتك الإسلامية',
    'preferences':          'التفضيلات',
    'community':            'المجتمع',
    'account_identity':     'الحساب والهوية',
    'account_sub':          'الاسم · البريد الإلكتروني · كلمة المرور',
    'notifications':        'الإشعارات',
    'notifications_sub':    'تنبيهات الصلاة · التذكيرات',
    'appearance':           'المظهر',
    'dark_mode':            'الوضع الداكن',
    'light_mode':           'الوضع الفاتح',
    'prayer_method':        'طريقة حساب الصلاة',
    'prayer_method_sub':    'رابطة الإسلام الشمالية · شافعي',
    'invite_friends':       'دعوة الأصدقاء',
    'invite_friends_sub':   'شارك سنة الفخامة',
    'rate_app':             'تقييم التطبيق',
    'rate_app_sub':         'انشر الخير',
    'support_us':           'ادعمنا',
    'support_us_sub':       'تسوق معنا أو شارك التطبيق',
    'sign_out':             'تسجيل الخروج',
    'pro_member':           'عضو مميز',
    'prayers_stat':         'صلوات',
    'streak':               'تسلسل',
    'days_fasted':          'أيام الصيام',
    'tasbeeh_stat':         'تسبيح',
    'guest_user':           'مستخدم ضيف',
    'anonymous_account':    'حساب مجهول',
    'verified_member':      'عضو موثق',
    'language_english':     'اللغة',
    'location_default':     'تحديد الموقع',
    // Media screen
    'islamic_content_library': 'مكتبة المحتوى الإسلامي',
    'choose_section':          'اختر قسماً',
    'islamic_videos':          'الفيديوهات الإسلامية',
    'islamic_videos_sub':      'المحاضرات · التفسير · التعليم · الأناشيد',
    'quran':                   'القرآن',
    'quran_sub':               'التلاوة · التجويد · الحفظ · التفسير',
    'ruqyah':                  'الرقية',
    'ruqyah_sub':              'تلاوات شفائية · الحماية · العين',
    'trending_now':            'الأكثر انتشاراً',
    'section_01':              'القسم ٠١',
    'section_02':              'القسم ٠٢',
    'section_03':              'القسم ٠٣',
    'videos':                  'فيديو',
    'surahs':                  'سور',
    'recitations':             'تلاوة',
    // Store screen
    'islamic_lifestyle':       'مستلزمات نمط الحياة الإسلامية',
    'featured_products':       'المنتجات المميزة',
    'ramadan_exclusive':       'إصدار رمضاني',
    'free_shipping':           'شحن مجاني عند ٣٠ جنيه+',
    'shop_now':                'تسوق الآن',
    'cat_all':                 'الكل',
    'cat_books':               'الكتب',
    'cat_clothing':            'الملابس',
    'cat_prayer':              'الصلاة',
    'cat_home':                'المنزل',
    'cat_jewellery':           'المجوهرات',
    // Auth screens
    'welcome_back':            'مرحباً بعودتك',
    'login_subtitle':          'سجّل دخولك لمتابعة رحلتك',
    'email':                   'البريد الإلكتروني',
    'password':                'كلمة المرور',
    'forgot_password':         'نسيت كلمة المرور؟',
    'login':                   'تسجيل الدخول',
    'no_account':              'ليس لديك حساب؟ ',
    'register_now':            'سجّل الآن',
    'fill_fields':             'يرجى ملء جميع الحقول',
    'login_failed':            'فشل تسجيل الدخول. يرجى التحقق من بيانات الاعتماد.',
    'create_account':          'إنشاء حساب',
    'register_subtitle':       'ابدأ رحلتك الإسلامية اليوم',
    'name':                    'الاسم الكامل',
    'register':                'تسجيل',
    'already_account':         'لديك حساب بالفعل؟ ',
    'sign_in':                 'تسجيل الدخول',
    'register_failed':         'فشل التسجيل. يرجى المحاولة مرة أخرى.',
    'email_required':          'البريد الإلكتروني مطلوب',
    'email_invalid':           'أدخل بريدًا إلكترونيًا صحيحًا',
    'password_required':       'كلمة المرور مطلوبة',
    'save_progress':           'احفظ تقدمك',
    'guest_register_sub':      'أنشئ حسابًا لمزامنة المفضلة والطلبات والإعدادات.',
    'join_community_sub':      'انضم إلى المجتمع. يستغرق أقل من دقيقة.',
    'guest_session_notice':    'سيتم الحفاظ على جلستك كضيف عند الترقية.',
    'continue_with_google':    'المتابعة عبر جوجل',
    'or_create_with_email':    'أو أنشئ حسابًا بالبريد الإلكتروني',
    'name_required':           'الاسم مطلوب',
    'name_too_short':          'الاسم قصير جدًا',
    'min_6_chars':             'الحد الأدنى 6 أحرف',
    'save_upgrade_account':    'حفظ وترقية الحساب',
    'enter_email_prompt':      'يرجى إدخال بريدك الإلكتروني',
    'reset_password_title':    'إعادة تعيين كلمة المرور',
    'reset_password_sub':      'أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور',
    'send_reset_link':         'إرسال رابط إعادة التعيين',
    'reset_link_sent':         'تم إرسال رابط إعادة التعيين إلى بريدك الإلكتروني',
    'reset_link_failed':       'فشل إرسال الرابط. يرجى المحاولة مرة أخرى.',
    // Zakat calculator
    'zakat_calc_tag':          'احسب زكاتك السنوية',
    'about_zakat':             'عن الزكاة',
    'about_zakat_body':        'تجب الزكاة عندما تبلغ ثروتك الخاضعة للزكاة النصاب '
        '(قيمة 85 غرامًا من الذهب) وتحول عليها الحول. أدخل '
        'أصولك أدناه لمعرفة المبلغ المستحق.',
    'your_zakatable_assets':   'أصولك الخاضعة للزكاة',
    'cash_savings':            'النقد والمدخرات',
    'cash_savings_hint':       'أرصدة البنك والنقد المتوفر',
    'gold_owned':              'الذهب الذي تملكه (غرام)',
    'gold_owned_hint':         'إجمالي وزن الذهب المملوك',
    'silver_owned':            'الفضة التي تملكها (غرام)',
    'silver_owned_hint':       'إجمالي وزن الفضة المملوكة',
    'business_assets':         'أصول العمل / المخزون',
    'business_assets_hint':    'قيمة المخزون والذمم المدينة',
    'other_investments':       'استثمارات أخرى',
    'other_investments_hint':  'الأسهم والعملات الرقمية وغيرها من الممتلكات الخاضعة للزكاة',
    'current_market_prices':   'أسعار السوق الحالية',
    'live_price_refresh':      'سعر مباشر — اضغط للتحديث',
    'tap_fetch_price':         'اضغط لجلب سعر اليوم',
    'gold_price_gram':         'سعر الذهب (لكل غرام)',
    'gold_price_gram_hint':    'يُستخدم لقيمة الذهب وحد النصاب',
    'silver_price_gram':       'سعر الفضة (لكل غرام)',
    'silver_price_gram_hint':  'يُستخدم لقيمة الفضة',
    'zakat_result':            'النتيجة',
    'total_zakatable_wealth':  'إجمالي الثروة الخاضعة للزكاة',
    'gold_silver_value':       'قيمة الذهب والفضة',
    'nisab_threshold':         'حد النصاب (85 غرام ذهب)',
    'zakat_due_this_year':     'الزكاة مستحقة هذا العام',
    'zakat_due_pct':           'الزكاة المستحقة (2.5%)',
    'below_nisab_notice':      'ثروتك الإجمالية أقل من حد النصاب — لا زكاة مستحقة هذا العام.',
    // Onboarding
    'enable_notifications':    'تفعيل الإشعارات',
    'notifications_desc':      'احصل على تنبيهات أوقات الصلاة وتذكيرات إسلامية',
    'enable_btn':              'تفعيل',
    'maybe_later':             'ربما لاحقاً',
    'set_location':            'تحديد موقعك',
    'location_desc':           'لأوقات صلاة دقيقة واتجاه القبلة',
    'detect_location':         'تحديد موقعي',
    // Settings
    'interface_language':      'لغة الواجهة',
    'select_language':         'اختر اللغة',
    'language_updated':        'تم تحديث اللغة',
    // Prayer tools
    'qibla':                   'القبلة',
    'qibla_sub':               'اتجاه مكة المكرمة',
    'tasbeeh_counter':         'عداد التسبيح',
    'reset':                   'إعادة ضبط',
    'forbidden_title':         'أوقات الصلاة المنهي عنها',
    'nearby_masjids':          'المساجد القريبة',
    // Notifications
    'prayer_alerts':           'تنبيهات الصلاة',
    'daily_reminder':          'التذكير اليومي',
    'enabled':                 'مفعّل',
    'disabled':                'معطّل',
    // Misc
    'share':                   'مشاركة',
    'add_to_cart':             'أضف إلى السلة',
    'checkout':                'الدفع',
    'order_confirmed':         'تم تأكيد الطلب',
    'continue_shopping':       'متابعة التسوق',
    'cart':                    'السلة',
    'your_cart':               'سلتك',
    'cart_empty_title':        'سلتك فارغة',
    'cart_empty_sub':          'أضف منتجات من المتجر للبدء.',
    'cart_review_sub':         'راجع اختياراتك قبل إتمام الشراء.',
    'order_summary':           'ملخص الطلب',
    'subtotal':                'المجموع الفرعي',
    'estimated_tax':           'الضريبة المقدرة',
    'shipping':                'الشحن',
    'free_shipping_usa':       'مجاني — في جميع أنحاء الولايات المتحدة',
    'total':                   'الإجمالي',
    'proceed_checkout':        'المتابعة إلى الدفع',
    'secure_checkout':         'دفع آمن ومشفر',
    'secure_checkout_title':   'الدفع الآمن',
    'contact_information':     'معلومات الاتصال',
    'full_name':               'الاسم الكامل',
    'email_address':           'البريد الإلكتروني',
    'phone_number':            'رقم الهاتف',
    'phone_required':          'رقم الهاتف مطلوب',
    'shipping_address':        'عنوان الشحن',
    'street_address':          'عنوان الشارع',
    'address_required':        'العنوان مطلوب',
    'city':                    'المدينة',
    'city_required':           'المدينة مطلوبة',
    'state_label':             'الولاية',
    'zip_postal_code':         'الرمز البريدي',
    'zip_required':            'الرمز البريدي مطلوب',
    'payment_method':          'طريقة الدفع',
    'cash_on_delivery':        'الدفع عند الاستلام',
    'country_label':           'البلد',
    'free_shipping_included':  'شحن مجاني',
    'powered_by_stripe':       'مدعوم بواسطة Stripe',
    'place_order_cod':         'تأكيد الطلب — الدفع عند الاستلام',
    'complete_order':          'إتمام الطلب',
    'subtotal_plus':           'المجموع الفرعي +',
    'tax_suffix':              'ضريبة',
    'ssl_encryption':          'تشفير SSL 256-بت',
    'your_items':              'مشترياتك',
    'visit_store':             'زيارة متجر سنة الفخامة',
    'limited_time_deal':       'عرض لفترة محدودة',
    'buy_new':                 'اشترِ جديدًا',
    'free_shipping_prefix':    'مجاني ',
    'free_shipping_line':      'شحن مجاني على كل عملية شراء',
    'free_delivery_usa':       'توصيل مجاني في جميع أنحاء الولايات المتحدة',
    'currently_unavailable':   'غير متوفر حاليًا',
    'in_stock':                'متوفر',
    'quantity_label':          'الكمية:',
    'add_to_cart_caps':        'أضف إلى السلة',
    'buy_now_caps':            'اشترِ الآن',
    'gift_wrap_prefix':        'أضف تغليف هدية فاخر مقابل ',
    'delivery_support':        'التوصيل والدعم',
    'select_to_learn_more':    'اختر لمعرفة المزيد',
    'ships_from':              'يُشحن من',
    'out_of_stock_caps':       'نفدت الكمية',
    'free_delivery':           'توصيل مجاني',
    'across_usa':              'في جميع أنحاء الولايات المتحدة',
    'returns_30day':           'إرجاع سهل',
    'returns':                 'خلال 30 يومًا',
    'customer':                'خدمة',
    'support':                 'العملاء',
    'browse':                  'تصفح',
    'no_products_category':    'لا توجد منتجات في هذه الفئة بعد.',
    'view_all_products':       'عرض جميع المنتجات',
    'categories_caps':         'الفئات',
    // Quran / Ruqyah / video screens
    'surahs_114':              '١١٤ سورة',
    'ayahs':                   'آيات',
    'surah':                   'سورة',
    'ayah':                    'آية',
    'quran_tab_sub':           'التلاوة · التجويد · الحفظ',
    'read_tab':                'قراءة',
    'watch_tab':               'مشاهدة',
    'continue_reading':        'متابعة القراءة',
    'all_recitations':         'كل التلاوات',
    'no_recitations_available': 'لا توجد تلاوات متاحة',
    'pull_refresh_hint':       'اسحب للأسفل للتحديث أو تحقق من اتصالك.',
    'featured_tilawah':        'تلاوة مميزة',
    'views':                   'مشاهدة',
    'ruqyah_tab_sub':          'الشفاء · الحماية · العين',
    'healing_through_quran':   'الشفاء بالقرآن',
    'ruqyah_info_body':        'استمع في مكان هادئ. التلاوات مبنية على السنة الصحيحة للشفاء والحماية.',
    'featured_caps':           'مميز',
    'listens':                 'استماع',
    'curated_content_prefix':  'محتوى إسلامي مُنتقى بعناية من ',
    'curated_content_suffix':  '. شاهد داخل التطبيق للحصول على التجربة الكاملة.',
    'video_unavailable':       'الفيديو غير متاح',
    'video_unavailable_body':  'قد يكون هذا الفيديو مقيدًا أو غير متاح.',
    'curated_youtube_feed':    'محتوى يوتيوب منتقى',
    'no_videos_yet':           'لا توجد فيديوهات بعد',
    'videos_will_appear':      'ستظهر الفيديوهات هنا بمجرد إضافتها.',
    // Hijri calendar
    'islamic_lunar_calendar_caps': 'التقويم الهجري الإسلامي',
    'ramadan_mubarak':         'رمضان مبارك',
    'ah_suffix':               'هـ',
    'eid':                     'عيد',
    'ramadan':                 'رمضان',
    // Forbidden times
    'makrooh_prayer_windows_caps': 'أوقات الصلاة المكروهة',
    'loading_prayer_times':    'جاري تحميل أوقات الصلاة...',
    'prayer_times_unavailable': 'أوقات الصلاة غير متاحة.',
    'sunrise_window':          'وقت الشروق',
    'after_fajr_avoid':        'بعد الفجر · تجنب الصلاة',
    'zawal_solar_noon':        'الزوال · منتصف النهار',
    'before_dhuhr_begins':     'قبل بدء الظهر',
    'sunset_window':           'وقت الغروب',
    'before_maghrib_avoid':    'قبل المغرب · تجنب الصلاة',
    'min_suffix':              'دقيقة',
    'about_makrooh_times':     'عن أوقات الكراهة',
    'makrooh_info_body':       'الصلاة خلال هذه الأوقات مكروهة في الفقه الإسلامي. هذه الأوقات مبنية على موقعك الحالي وجدول صلاة اليوم.',
    'todays_windows_caps':     'أوقات اليوم',
    'upcoming':                'قادم',
    'to_prefix':               'إلى',
    'duration_prefix':         'المدة:',
    'scholarly_reference_caps': 'المرجع الشرعي',
    'window_prefix':           'الفترة',
    'passed_today':            'انتهى اليوم',
    // Masjid Finder
    'could_not_open_navigation': 'تعذر فتح الملاحة.',
    'masjid_finder_coming_soon': 'محدد المساجد — قريبًا',
    'masjid_coming_soon_body': 'البحث عن المساجد القريبة قيد الإعداد وسيكون متاحًا قريبًا.',
    'search_mosques_hint':     'ابحث عن مساجد، مدينة...',
    'searching_mosques':       'جاري البحث عن المساجد...',
    'no_mosques_found':        'لم يتم العثور على مساجد',
    'mosque_singular_nearby':  'مسجد قريب',
    'mosques_plural_nearby':   'مساجد قريبة',
    'sorted_by_distance':      'مرتبة حسب المسافة',
    'finding_nearby_mosques':  'جاري البحث عن المساجد القريبة...',
    'no_mosques_found_nearby': 'لم يتم العثور على مساجد قريبة',
    'try_different_area':      'جرب البحث في منطقة أو مدينة أخرى',
    'open_status':             'مفتوح',
    'closed_status':           'مغلق',
    'address_label':           'العنوان',
    'distance_label':          'المسافة',
    'status_label':            'الحالة',
    'unknown_label':           'غير معروف',
    'open_now_label':          'مفتوح الآن',
    'get_directions':          'الحصول على الاتجاهات',
    // Adhan settings
    'adhan_sound_coming_soon': 'صوت الأذان هذا غير متاح بعد — قريبًا.',
    'adhan_alarms_activated':  'تم تفعيل تنبيهات الأذان.',
    'prayer_alarms':           'تنبيهات الصلاة',
    'adhan_sound':             'صوت الأذان',
    'volume_label':            'مستوى الصوت',
    'calculation_method':      'طريقة الحساب',
    'madhab_school':           'المذهب الفقهي',
    'additional_options':      'خيارات إضافية',
    'activate_adhan_alarms':   'تفعيل تنبيهات الأذان',
    'adhan_settings_title':    'إعدادات الأذان',
    'prayer_alarms_preferences_sub': 'تنبيهات الصلاة والتفضيلات',
    'on_label':                'مفعّل',
    'off_label':               'معطّل',
    'five_daily_prayers':      '٥ صلوات يومية',
    'adhan_alarms_label':      'تنبيهات الأذان',
    'adhan_ring_each_prayer':  'سيُسمع الأذان في كل وقت صلاة',
    'tap_enable_adhan':        'اضغط لتفعيل إشعارات الأذان',
    'alarm_enabled':           'التنبيه مفعّل',
    'alarm_disabled':          'التنبيه معطّل',
    'later_asr_time':          'وقت عصر متأخر',
    'earlier_asr_time':        'وقت عصر مبكر',
    'vibration_label':         'الاهتزاز',
    'vibrate_device_sub':      'اهتزاز الجهاز عند رنين التنبيه',
    'pre_prayer_reminder':     'تذكير قبل الصلاة',
    'pre_prayer_reminder_sub': 'إشعار قبل 10 دقائق من كل صلاة',
    // Support Us / Location / Prayer Method / Appearance / Account / Invite / Rate
    'help_us_grow_caps':       'ساعدنا على النمو',
    'support_prefix':          'ادعم ',
    'support_body':            'كل عملية شراء من متجرنا وكل صديق تخبره عن التطبيق يدعم مباشرة مهمتنا لبناء أدوات مدروسة لخدمة المجتمع المسلم.',
    'shop_with_us':            'تسوق معنا',
    'shop_with_us_sub':        'كل طلب يمول المنتجات التي سنطورها لاحقًا.',
    'share_the_app':           'شارك التطبيق',
    'share_the_app_sub':       'أخبر صديقًا أو أحد أفراد العائلة عنا.',
    'share_message_prefix':    'أستخدم ',
    'share_message_suffix':    ' لأوقات الصلاة والقبلة والتذكيرات اليومية — جربه!',
    'browse_the_shop':         'تصفح المتجر',
    'location_updated':        'تم تحديث الموقع',
    'location_set_to_prefix':  'تم تعيين الموقع إلى ',
    'prayer_time_calibration_caps': 'معايرة وقت الصلاة',
    'no_location_set':         'لم يتم تحديد الموقع',
    'using_london_fallback':   'استخدام لندن كموقع افتراضي',
    'active_label':            'نشط',
    'default_label':           'افتراضي',
    'gps_caps':                'GPS',
    'use_current_location':    'استخدام الموقع الحالي',
    'detects_city_via_gps':    'يكتشف مدينتك عبر GPS',
    'search_city_caps':        'ابحث عن مدينة',
    'search_for_city_hint':    'ابحث عن مدينة...',
    'popular_cities_caps':     'مدن شائعة',
    'prayer_method_saved':     'تم حفظ طريقة الصلاة.',
    'calculation_madhab_caps': 'الحساب والمذهب',
    'current_prefix':          'الحالي: ',
    'affects_asr_twilight':    'يؤثر على توقيت العصر وحسابات الشفق في منطقتك.',
    'asr_madhab_caps':         'مذهب العصر',
    'earlier_asr':             'عصر مبكر',
    'later_asr':               'عصر متأخر',
    'save_prayer_method':      'حفظ طريقة الصلاة',
    'text_size_small':         'صغير',
    'text_size_default':       'افتراضي',
    'text_size_large':         'كبير',
    'text_size_extra_large':   'كبير جدًا',
    'theme_display_caps':      'المظهر والعرض',
    'theme_mode_caps':         'وضع المظهر',
    'use_system_default':      'استخدام إعداد النظام',
    'match_device_appearance': 'مطابقة مظهر الجهاز',
    'text_size_caps':          'حجم النص',
    'profile_updated_success': 'تم تحديث الملف الشخصي بنجاح',
    'profile_update_failed':   'فشل تحديث الملف الشخصي',
    'change_password':         'تغيير كلمة المرور',
    'send_reset_link_to_prefix': 'إرسال رابط إعادة تعيين كلمة المرور إلى ',
    'send_link':               'إرسال الرابط',
    'reset_link_sent_to_prefix': 'تم إرسال رابط إعادة التعيين إلى ',
    'failed_send_reset_link':  'فشل إرسال رابط إعادة التعيين',
    'personal_information_caps': 'المعلومات الشخصية',
    'guest_label':             'ضيف',
    'personal_details_caps':   'التفاصيل الشخصية',
    'security_caps':           'الأمان',
    'no_email_on_account':     'لا يوجد بريد إلكتروني على هذا الحساب',
    'danger_zone_caps':        'منطقة الخطر',
    'delete_account':          'حذف الحساب',
    'delete_account_confirm_body': 'هل أنت متأكد أنك تريد حذف حسابك نهائيًا؟ لا يمكن التراجع عن هذا الإجراء.',
    'delete':                  'حذف',
    'share_msg_body':          'انضم إليّ في سنة الفخامة — رفيقك في نمط الحياة الإسلامي!',
    'could_not_open_app':      'تعذر فتح هذا التطبيق.',
    'share_sunnah_grandeur_caps': 'شارك سنة الفخامة',
    'spread_the_khair':        'انشر الخير',
    'spread_khair_body':       'شارك سنة الفخامة مع الأصدقاء والعائلة. كل عمل خير يبدأ بتذكير.',
    'your_invite_link_caps':   'رابط دعوتك',
    'link_copied':             'تم نسخ الرابط!',
    'share_via_caps':          'شارك عبر',
    'sunnah_grandeur_app_label': 'تطبيق سنة الفخامة',
    'share_app_link':          'شارك رابط التطبيق',
    'tap_star_first':          'اضغط على نجمة لاختيار تقييم أولاً.',
    'could_not_submit_feedback': 'تعذر إرسال الملاحظات',
    'spread_the_khair_caps':   'انشر الخير',
    'enjoying_the_app':        'هل تستمتع بالتطبيق؟',
    'rating_helps_discover':   'تقييمك يساعد مسلمين آخرين على اكتشاف سنة الفخامة. يستغرق الأمر 10 ثوانٍ فقط.',
    'rate_app_hint':           'ما الذي يعجبك أكثر في سنة الفخامة؟ (اختياري)',
    'feedback_sent':           'تم إرسال الملاحظات',
    'submit_feedback':         'إرسال الملاحظات',
    'jazakallah_khair':        'جزاك الله خيرًا على ملاحظاتك 🤍',
    'feedback_goes_to_team':   'تصل ملاحظاتك مباشرة إلى فريقنا.',
  },

  // ─────────────────────────────────────────────────────────── BANGLA ──
  'bn': {
    // Global / nav
    'app_name':        'সুন্নাহ গ্র্যান্ডার',
    'tagline':         'নবীজির পথে জীবন যাপন',
    'muslim_productivity_tag': 'মুসলিম প্রোডাক্টিভিটি, সুন্নাহ গ্র্যান্ডার থেকে',
    'home':            'হোম',
    'media':           'মিডিয়া',
    'store':           'স্টোর',
    'profile':         'প্রোফাইল',
    'language':        'ভাষা',
    'location':        'অবস্থান',
    'settings':        'সেটিংস',
    'apply':           'প্রয়োগ করুন',
    'continue':        'চালিয়ে যান',
    'skip':            'এখন এড়িয়ে যান',
    'save':            'সংরক্ষণ',
    'cancel':          'বাতিল',
    'done':            'সম্পন্ন',
    'search':          'অনুসন্ধান',
    'back':            'পিছনে',
    'close':           'বন্ধ',
    'loading':         'লোড হচ্ছে...',
    'error':           'কিছু একটা ভুল হয়েছে',
    'retry':           'আবার চেষ্টা করুন',
    'in':              'পরে',
    // Language onboarding
    'select_lang':     'আপনার ভাষা বেছে নিন',
    'select_lang_sub': 'আপনার পছন্দের ভাষা নির্বাচন করুন\nযাত্রা শুরু করতে',
    'continue_with':   'এগিয়ে যান',
    // Home screen
    'daily_inspiration': 'দৈনিক অনুপ্রেরণা',
    'hadith':            'হাদিস',
    'sawm':              'সাওম',
    'active':            'সক্রিয়',
    'quick_access':      'দ্রুত অ্যাক্সেস',
    'next_prayer':       'পরবর্তী নামাজ',
    'namaz_schedule':    'নামাজের সময়সূচি',
    'five_prayer_times': '৫ ওয়াক্ত নামাজ',
    'forbidden_times':   'নিষিদ্ধ সময়',
    'makrooh_windows':   'মাকরুহ সময়',
    'qibla_finder':      'কিবলা নির্ণয়',
    'live_compass':      'লাইভ কম্পাস',
    'tasbeeh':           'তাসবিহ',
    'digital_dhikr':     'ডিজিটাল জিকর',
    'masjid_finder':     'মসজিদ খুঁজুন',
    'mosques_nearby':    'আপনার কাছের মসজিদ খুঁজুন',
    'zakat_calculator':  'যাকাত ক্যালকুলেটর',
    'calculate_zakat_due': 'আপনার যাকাত হিসাব করুন',
    'hijri_calendar':    'হিজরি ক্যালেন্ডার',
    'islamic_lunar_dates': 'ইসলামিক চান্দ্র তারিখ',
    'i_fasted_today':    'আজ রোজা রেখেছি',
    'sehri':             'সেহরি',
    'iftar':             'ইফতার',
    'today':             'আজ',
    'added_today':       'আজ যোগ হয়েছে',
    'calculation':       'হিসাব',
    // Prayer times
    'prayer_times':    'নামাজের সময়',
    'fajr':            'ফজর',
    'dhuhr':           'যোহর',
    'asr':             'আসর',
    'maghrib':         'মাগরিব',
    'isha':            'এশা',
    'sunrise':         'সূর্যোদয়',
    'sunset':          'সূর্যাস্ত',
    'all_prayers':     'সব নামাজের সময়',
    // Profile screen
    'your_islamic_journey': 'আপনার ইসলামি যাত্রা',
    'preferences':          'পছন্দসমূহ',
    'community':            'সম্প্রদায়',
    'account_identity':     'অ্যাকাউন্ট ও পরিচয়',
    'account_sub':          'নাম · ইমেইল · পাসওয়ার্ড',
    'notifications':        'বিজ্ঞপ্তি',
    'notifications_sub':    'নামাজের সতর্কতা · রিমাইন্ডার',
    'appearance':           'উপস্থিতি',
    'dark_mode':            'ডার্ক মোড',
    'light_mode':           'লাইট মোড',
    'prayer_method':        'নামাজ হিসাবের পদ্ধতি',
    'prayer_method_sub':    'ISNA · শাফেয়ি',
    'invite_friends':       'বন্ধুদের আমন্ত্রণ জানান',
    'invite_friends_sub':   'সুন্নাহ গ্র্যান্ডার শেয়ার করুন',
    'rate_app':             'অ্যাপ রেটিং দিন',
    'rate_app_sub':         'কল্যাণ ছড়িয়ে দিন',
    'support_us':           'আমাদের সাহায্য করুন',
    'support_us_sub':       'আমাদের থেকে কিনুন অথবা অ্যাপটি শেয়ার করুন',
    'sign_out':             'সাইন আউট',
    'pro_member':           'প্রো সদস্য',
    'prayers_stat':         'নামাজ',
    'streak':               'ধারাবাহিকতা',
    'days_fasted':          'রোজার দিন',
    'tasbeeh_stat':         'তাসবিহ',
    'guest_user':           'অতিথি ব্যবহারকারী',
    'anonymous_account':    'বেনামী অ্যাকাউন্ট',
    'verified_member':      'যাচাইকৃত সদস্য',
    'language_english':     'ভাষা',
    'location_default':     'অবস্থান নির্ধারণ করুন',
    // Media screen
    'islamic_content_library': 'ইসলামিক কন্টেন্ট লাইব্রেরি',
    'choose_section':          'একটি বিভাগ বেছে নিন',
    'islamic_videos':          'ইসলামিক ভিডিও',
    'islamic_videos_sub':      'বক্তৃতা · তাফসির · শিক্ষা · নাশিদ',
    'quran':                   'কুরআন',
    'quran_sub':               'তিলাওয়াত · তাজওয়িদ · হিফজ · তাফসির',
    'ruqyah':                  'রুকইয়াহ',
    'ruqyah_sub':              'নিরাময় তিলাওয়াত · সুরক্ষা · নজর',
    'trending_now':            'এখন ট্রেন্ডিং',
    'section_01':              'বিভাগ ০১',
    'section_02':              'বিভাগ ০২',
    'section_03':              'বিভাগ ০৩',
    'videos':                  'ভিডিও',
    'surahs':                  'সূরা',
    'recitations':             'তিলাওয়াত',
    // Store screen
    'islamic_lifestyle':       'ইসলামিক জীবনযাত্রার পণ্য',
    'featured_products':       'বৈশিষ্ট্যযুক্ত পণ্য',
    'ramadan_exclusive':       'রমজান এক্সক্লুসিভ',
    'free_shipping':           '£৩০+ এ বিনামূল্যে শিপিং',
    'shop_now':                'এখন কিনুন',
    'cat_all':                 'সব',
    'cat_books':               'বই',
    'cat_clothing':            'পোশাক',
    'cat_prayer':              'নামাজ',
    'cat_home':                'গৃহ',
    'cat_jewellery':           'গহনা',
    // Auth screens
    'welcome_back':            'আবার স্বাগতম',
    'login_subtitle':          'আপনার যাত্রা চালিয়ে যেতে লগ ইন করুন',
    'email':                   'ইমেইল',
    'password':                'পাসওয়ার্ড',
    'forgot_password':         'পাসওয়ার্ড ভুলে গেছেন?',
    'login':                   'লগ ইন',
    'no_account':              'অ্যাকাউন্ট নেই? ',
    'register_now':            'এখনই নিবন্ধন করুন',
    'fill_fields':             'সকল ঘর পূরণ করুন',
    'login_failed':            'লগইন ব্যর্থ হয়েছে। আপনার তথ্য যাচাই করুন।',
    'create_account':          'অ্যাকাউন্ট তৈরি করুন',
    'register_subtitle':       'আজই আপনার ইসলামিক যাত্রা শুরু করুন',
    'name':                    'পূর্ণ নাম',
    'register':                'নিবন্ধন করুন',
    'already_account':         'ইতিমধ্যে অ্যাকাউন্ট আছে? ',
    'sign_in':                 'সাইন ইন',
    'register_failed':         'নিবন্ধন ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    'email_required':          'ইমেইল আবশ্যক',
    'email_invalid':           'একটি সঠিক ইমেইল দিন',
    'password_required':       'পাসওয়ার্ড আবশ্যক',
    'save_progress':           'আপনার অগ্রগতি সংরক্ষণ করুন',
    'guest_register_sub':      'আপনার পছন্দ, অর্ডার ও সেটিংস সিঙ্ক করতে একটি অ্যাকাউন্ট তৈরি করুন।',
    'join_community_sub':      'কমিউনিটিতে যোগ দিন। এক মিনিটেরও কম সময় লাগে।',
    'guest_session_notice':    'আপগ্রেড করার সময় আপনার গেস্ট সেশন সংরক্ষিত থাকবে।',
    'continue_with_google':    'গুগল দিয়ে চালিয়ে যান',
    'or_create_with_email':    'অথবা ইমেইল দিয়ে অ্যাকাউন্ট তৈরি করুন',
    'name_required':           'নাম আবশ্যক',
    'name_too_short':          'নামটি খুব ছোট',
    'min_6_chars':             'ন্যূনতম ৬ অক্ষর',
    'save_upgrade_account':    'সংরক্ষণ ও অ্যাকাউন্ট আপগ্রেড করুন',
    'enter_email_prompt':      'অনুগ্রহ করে আপনার ইমেইল দিন',
    'reset_password_title':    'পাসওয়ার্ড রিসেট করুন',
    'reset_password_sub':      'পাসওয়ার্ড রিসেট লিঙ্ক পেতে আপনার ইমেইল দিন',
    'send_reset_link':         'রিসেট লিঙ্ক পাঠান',
    'reset_link_sent':         'পাসওয়ার্ড রিসেট লিঙ্ক আপনার ইমেইলে পাঠানো হয়েছে',
    'reset_link_failed':       'লিঙ্ক পাঠাতে ব্যর্থ। আবার চেষ্টা করুন।',
    // Zakat calculator
    'zakat_calc_tag':          'আপনার বার্ষিক যাকাত হিসাব করুন',
    'about_zakat':             'যাকাত সম্পর্কে',
    'about_zakat_body':        'আপনার মোট যাকাতযোগ্য সম্পদ নিসাব '
        '(৮৫ গ্রাম স্বর্ণের মূল্য) পৌঁছালে এবং এক চন্দ্র বছর ধরে থাকলে যাকাত ফরজ হয়। '
        'আপনার প্রদেয় যাকাত জানতে নিচে সম্পদের তথ্য দিন।',
    'your_zakatable_assets':   'আপনার যাকাতযোগ্য সম্পদ',
    'cash_savings':            'নগদ ও সঞ্চয়',
    'cash_savings_hint':       'ব্যাংক ব্যালেন্স, হাতে নগদ',
    'gold_owned':              'আপনার মালিকানাধীন স্বর্ণ (গ্রাম)',
    'gold_owned_hint':         'মালিকানাধীন স্বর্ণের মোট ওজন',
    'silver_owned':            'আপনার মালিকানাধীন রূপা (গ্রাম)',
    'silver_owned_hint':       'মালিকানাধীন রূপার মোট ওজন',
    'business_assets':         'ব্যবসায়িক সম্পদ / মজুদ',
    'business_assets_hint':    'পণ্য মজুদ ও পাওনার মূল্য',
    'other_investments':       'অন্যান্য বিনিয়োগ',
    'other_investments_hint':  'শেয়ার, ক্রিপ্টো, অন্যান্য যাকাতযোগ্য সম্পদ',
    'current_market_prices':   'বর্তমান বাজার মূল্য',
    'live_price_refresh':      'লাইভ মূল্য — রিফ্রেশ করতে ট্যাপ করুন',
    'tap_fetch_price':         'আজকের মূল্য আনতে ট্যাপ করুন',
    'gold_price_gram':         'স্বর্ণের মূল্য (প্রতি গ্রাম)',
    'gold_price_gram_hint':    'স্বর্ণের মূল্য ও নিসাব নির্ধারণে ব্যবহৃত',
    'silver_price_gram':       'রূপার মূল্য (প্রতি গ্রাম)',
    'silver_price_gram_hint':  'রূপার মূল্য নির্ধারণে ব্যবহৃত',
    'zakat_result':            'ফলাফল',
    'total_zakatable_wealth':  'মোট যাকাতযোগ্য সম্পদ',
    'gold_silver_value':       'স্বর্ণ + রূপার মূল্য',
    'nisab_threshold':         'নিসাব সীমা (৮৫ গ্রাম স্বর্ণ)',
    'zakat_due_this_year':     'এই বছর যাকাত ফরজ',
    'zakat_due_pct':           'প্রদেয় যাকাত (২.৫%)',
    'below_nisab_notice':      'আপনার মোট সম্পদ নিসাব সীমার নিচে — এই বছর যাকাত ফরজ নয়।',
    // Onboarding
    'enable_notifications':    'বিজ্ঞপ্তি চালু করুন',
    'notifications_desc':      'নামাজের সময়ের সতর্কতা ও ইসলামিক রিমাইন্ডার পান',
    'enable_btn':              'চালু করুন',
    'maybe_later':             'পরে হয়তো',
    'set_location':            'আপনার অবস্থান নির্ধারণ করুন',
    'location_desc':           'সঠিক নামাজের সময় ও কিবলার দিকের জন্য',
    'detect_location':         'আমার অবস্থান শনাক্ত করুন',
    // Settings
    'interface_language':      'ইন্টারফেস ভাষা',
    'select_language':         'ভাষা নির্বাচন করুন',
    'language_updated':        'ভাষা আপডেট হয়েছে',
    // Prayer tools
    'qibla':                   'কিবলা',
    'qibla_sub':               'মক্কার দিক',
    'tasbeeh_counter':         'তাসবিহ কাউন্টার',
    'reset':                   'রিসেট',
    'forbidden_title':         'নিষিদ্ধ নামাজের সময়',
    'nearby_masjids':          'কাছের মসজিদ',
    // Notifications
    'prayer_alerts':           'নামাজের সতর্কতা',
    'daily_reminder':          'দৈনিক রিমাইন্ডার',
    'enabled':                 'সক্রিয়',
    'disabled':                'নিষ্ক্রিয়',
    // Misc
    'share':                   'শেয়ার',
    'add_to_cart':             'কার্টে যোগ করুন',
    'checkout':                'চেকআউট',
    'order_confirmed':         'অর্ডার নিশ্চিত হয়েছে',
    'continue_shopping':       'কেনাকাটা চালিয়ে যান',
    'cart':                    'কার্ট',
    'your_cart':               'আপনার কার্ট',
    'cart_empty_title':        'আপনার কার্ট খালি',
    'cart_empty_sub':          'শুরু করতে দোকান থেকে পণ্য যোগ করুন।',
    'cart_review_sub':         'কেনাকাটা সম্পূর্ণ করার আগে আপনার নির্বাচনগুলো পর্যালোচনা করুন।',
    'order_summary':           'অর্ডার সারাংশ',
    'subtotal':                'সাবটোটাল',
    'estimated_tax':           'আনুমানিক কর',
    'shipping':                'শিপিং',
    'free_shipping_usa':       'বিনামূল্যে — সারা যুক্তরাষ্ট্র জুড়ে',
    'total':                   'মোট',
    'proceed_checkout':        'চেকআউটে যান',
    'secure_checkout':         'নিরাপদ এনক্রিপ্টেড চেকআউট',
    'secure_checkout_title':   'নিরাপদ চেকআউট',
    'contact_information':     'যোগাযোগের তথ্য',
    'full_name':               'পূর্ণ নাম',
    'email_address':           'ইমেইল ঠিকানা',
    'phone_number':            'ফোন নম্বর',
    'phone_required':          'ফোন নম্বর আবশ্যক',
    'shipping_address':        'শিপিং ঠিকানা',
    'street_address':          'রাস্তার ঠিকানা',
    'address_required':        'ঠিকানা আবশ্যক',
    'city':                    'শহর',
    'city_required':           'শহর আবশ্যক',
    'state_label':             'রাজ্য',
    'zip_postal_code':         'জিপ / পোস্টাল কোড',
    'zip_required':            'জিপ কোড আবশ্যক',
    'payment_method':          'পেমেন্ট পদ্ধতি',
    'cash_on_delivery':        'ক্যাশ অন ডেলিভারি',
    'country_label':           'দেশ',
    'free_shipping_included':  'ফ্রি শিপিং অন্তর্ভুক্ত',
    'powered_by_stripe':       'Stripe দ্বারা পরিচালিত',
    'place_order_cod':         'অর্ডার করুন — ডেলিভারিতে পরিশোধ',
    'complete_order':          'অর্ডার সম্পন্ন করুন',
    'subtotal_plus':           'সাবটোটাল +',
    'tax_suffix':              'কর',
    'ssl_encryption':          '২৫৬-বিট SSL এনক্রিপশন',
    'your_items':              'আপনার আইটেম',
    'visit_store':             'সুন্নাহ গ্র্যান্ডার স্টোর দেখুন',
    'limited_time_deal':       'সীমিত সময়ের অফার',
    'buy_new':                 'নতুন কিনুন',
    'free_shipping_prefix':    'ফ্রি ',
    'free_shipping_line':      'প্রতিটি ক্রয়ে শিপিং',
    'free_delivery_usa':       'সারা যুক্তরাষ্ট্রে ফ্রি ডেলিভারি',
    'currently_unavailable':   'বর্তমানে অনুপলব্ধ',
    'in_stock':                'স্টকে আছে',
    'quantity_label':          'পরিমাণ:',
    'add_to_cart_caps':        'কার্টে যোগ করুন',
    'buy_now_caps':            'এখনই কিনুন',
    'gift_wrap_prefix':        'প্রিমিয়াম গিফট র‍্যাপিং যোগ করুন মাত্র ',
    'delivery_support':        'ডেলিভারি ও সহায়তা',
    'select_to_learn_more':    'আরও জানতে নির্বাচন করুন',
    'ships_from':              'পাঠানো হয়',
    'out_of_stock_caps':       'স্টক নেই',
    'free_delivery':           'ফ্রি ডেলিভারি',
    'across_usa':              'সারা যুক্তরাষ্ট্রে',
    'returns_30day':           '৩০-দিনের সহজ',
    'returns':                 'রিটার্ন',
    'customer':                'গ্রাহক',
    'support':                 'সহায়তা',
    'browse':                  'ব্রাউজ করুন',
    'no_products_category':    'এই ক্যাটাগরিতে এখনও কোনো পণ্য নেই।',
    'view_all_products':       'সব পণ্য দেখুন',
    'categories_caps':         'ক্যাটাগরি',
    // Quran / Ruqyah / video screens
    'surahs_114':              '১১৪টি সূরা',
    'ayahs':                   'আয়াত',
    'surah':                   'সূরা',
    'ayah':                    'আয়াত',
    'quran_tab_sub':           'তিলাওয়াত · তাজওয়িদ · হিফজ',
    'read_tab':                'পড়ুন',
    'watch_tab':               'দেখুন',
    'continue_reading':        'পড়া চালিয়ে যান',
    'all_recitations':         'সব তিলাওয়াত',
    'no_recitations_available': 'কোনো তিলাওয়াত পাওয়া যায়নি',
    'pull_refresh_hint':       'রিফ্রেশ করতে নিচে টানুন অথবা সংযোগ পরীক্ষা করুন।',
    'featured_tilawah':        'বিশেষ তিলাওয়াত',
    'views':                   'ভিউ',
    'ruqyah_tab_sub':          'নিরাময় · সুরক্ষা · নজর',
    'healing_through_quran':   'কুরআনের মাধ্যমে নিরাময়',
    'ruqyah_info_body':        'শান্ত জায়গায় শুনুন। তিলাওয়াতগুলো নিরাময় ও সুরক্ষার জন্য প্রামাণিক সুন্নাহর উপর ভিত্তি করে তৈরি।',
    'featured_caps':           'বিশেষ',
    'listens':                 'শ্রবণ',
    'curated_content_prefix':  'যত্ন সহকারে নির্বাচিত ইসলামিক কন্টেন্ট থেকে ',
    'curated_content_suffix':  '। সম্পূর্ণ অভিজ্ঞতার জন্য অ্যাপে দেখুন।',
    'video_unavailable':       'ভিডিও অনুপলব্ধ',
    'video_unavailable_body':  'এই ভিডিওটি সীমাবদ্ধ বা অনুপলব্ধ হতে পারে।',
    'curated_youtube_feed':    'নির্বাচিত ইউটিউব ফিড',
    'no_videos_yet':           'এখনও কোনো ভিডিও নেই',
    'videos_will_appear':      'যোগ করা হলে ভিডিওগুলো এখানে দেখা যাবে।',
    // Hijri calendar
    'islamic_lunar_calendar_caps': 'ইসলামিক চান্দ্র ক্যালেন্ডার',
    'ramadan_mubarak':         'রমজান মুবারক',
    'ah_suffix':               'হিজরি',
    'eid':                     'ঈদ',
    'ramadan':                 'রমজান',
    // Forbidden times
    'makrooh_prayer_windows_caps': 'মাকরুহ নামাজের সময়',
    'loading_prayer_times':    'নামাজের সময় লোড হচ্ছে...',
    'prayer_times_unavailable': 'নামাজের সময় পাওয়া যায়নি।',
    'sunrise_window':          'সূর্যোদয়ের সময়',
    'after_fajr_avoid':        'ফজরের পর · নামাজ এড়িয়ে চলুন',
    'zawal_solar_noon':        'যাওয়াল · মধ্যাহ্ন',
    'before_dhuhr_begins':     'যোহর শুরুর আগে',
    'sunset_window':           'সূর্যাস্তের সময়',
    'before_maghrib_avoid':    'মাগরিবের আগে · নামাজ এড়িয়ে চলুন',
    'min_suffix':              'মিনিট',
    'about_makrooh_times':     'মাকরুহ সময় সম্পর্কে',
    'makrooh_info_body':       'এই সময়গুলোতে নামাজ পড়া ইসলামি ফিকহে মাকরুহ। এই সময়গুলো আপনার বর্তমান অবস্থান ও আজকের নামাজের সময়সূচির ভিত্তিতে নির্ধারিত।',
    'todays_windows_caps':     'আজকের সময়সমূহ',
    'upcoming':                'আসন্ন',
    'to_prefix':               'থেকে',
    'duration_prefix':         'সময়কাল:',
    'scholarly_reference_caps': 'শরিয়াহ রেফারেন্স',
    'window_prefix':           'উইন্ডো',
    'passed_today':            'আজ শেষ হয়েছে',
    // Masjid Finder
    'could_not_open_navigation': 'নেভিগেশন খোলা যায়নি।',
    'masjid_finder_coming_soon': 'মসজিদ খুঁজুন — শীঘ্রই আসছে',
    'masjid_coming_soon_body': 'কাছের মসজিদ অনুসন্ধান প্রস্তুত করা হচ্ছে এবং শীঘ্রই উপলব্ধ হবে।',
    'search_mosques_hint':     'মসজিদ, শহর খুঁজুন...',
    'searching_mosques':       'মসজিদ খোঁজা হচ্ছে...',
    'no_mosques_found':        'কোনো মসজিদ পাওয়া যায়নি',
    'mosque_singular_nearby':  'মসজিদ কাছাকাছি',
    'mosques_plural_nearby':   'মসজিদ কাছাকাছি',
    'sorted_by_distance':      'দূরত্ব অনুসারে সাজানো',
    'finding_nearby_mosques':  'কাছের মসজিদ খোঁজা হচ্ছে...',
    'no_mosques_found_nearby': 'কাছাকাছি কোনো মসজিদ পাওয়া যায়নি',
    'try_different_area':      'ভিন্ন এলাকা বা শহরে খোঁজার চেষ্টা করুন',
    'open_status':             'খোলা',
    'closed_status':           'বন্ধ',
    'address_label':           'ঠিকানা',
    'distance_label':          'দূরত্ব',
    'status_label':            'অবস্থা',
    'unknown_label':           'অজানা',
    'open_now_label':          'এখন খোলা',
    'get_directions':          'দিকনির্দেশ নিন',
    // Adhan settings
    'adhan_sound_coming_soon': 'এই আজানের শব্দটি এখনো উপলব্ধ নয় — শীঘ্রই আসছে।',
    'adhan_alarms_activated':  'আজান অ্যালার্ম সক্রিয় হয়েছে।',
    'prayer_alarms':           'নামাজের অ্যালার্ম',
    'adhan_sound':             'আজানের শব্দ',
    'volume_label':            'ভলিউম',
    'calculation_method':      'হিসাব পদ্ধতি',
    'madhab_school':           'মাযহাব / ফিকহ',
    'additional_options':      'অতিরিক্ত অপশন',
    'activate_adhan_alarms':   'আজান অ্যালার্ম সক্রিয় করুন',
    'adhan_settings_title':    'আজান সেটিংস',
    'prayer_alarms_preferences_sub': 'নামাজের অ্যালার্ম ও পছন্দসমূহ',
    'on_label':                'চালু',
    'off_label':               'বন্ধ',
    'five_daily_prayers':      '৫ ওয়াক্ত দৈনিক নামাজ',
    'adhan_alarms_label':      'আজান অ্যালার্ম',
    'adhan_ring_each_prayer':  'প্রতিটি নামাজের সময় আজান বাজবে',
    'tap_enable_adhan':        'আজান বিজ্ঞপ্তি চালু করতে ট্যাপ করুন',
    'alarm_enabled':           'অ্যালার্ম চালু',
    'alarm_disabled':          'অ্যালার্ম বন্ধ',
    'later_asr_time':          'দেরিতে আসরের সময়',
    'earlier_asr_time':        'আগে আসরের সময়',
    'vibration_label':         'কম্পন',
    'vibrate_device_sub':      'অ্যালার্ম বাজলে ডিভাইস কম্পিত হবে',
    'pre_prayer_reminder':     'নামাজের পূর্ব রিমাইন্ডার',
    'pre_prayer_reminder_sub': 'প্রতিটি নামাজের ১০ মিনিট আগে বিজ্ঞপ্তি',
    // Support Us / Location / Prayer Method / Appearance / Account / Invite / Rate
    'help_us_grow_caps':       'আমাদের বাড়তে সাহায্য করুন',
    'support_prefix':          'সমর্থন করুন ',
    'support_body':            'আমাদের দোকান থেকে প্রতিটি ক্রয় এবং অ্যাপ সম্পর্কে আপনি যে বন্ধুকে বলেন তা সরাসরি মুসলিম সম্প্রদায়ের জন্য চিন্তাশীল টুল তৈরির আমাদের লক্ষ্যে সহায়তা করে।',
    'shop_with_us':            'আমাদের থেকে কিনুন',
    'shop_with_us_sub':        'প্রতিটি অর্ডার আমাদের পরবর্তী পণ্যকে অর্থায়ন করে।',
    'share_the_app':           'অ্যাপটি শেয়ার করুন',
    'share_the_app_sub':       'একজন বন্ধু বা পরিবারের সদস্যকে আমাদের সম্পর্কে বলুন।',
    'share_message_prefix':    'আমি ব্যবহার করি ',
    'share_message_suffix':    ' নামাজের সময়, কিবলা এবং দৈনিক রিমাইন্ডারের জন্য — দেখে নিন!',
    'browse_the_shop':         'দোকান ব্রাউজ করুন',
    'location_updated':        'অবস্থান আপডেট হয়েছে',
    'location_set_to_prefix':  'অবস্থান নির্ধারণ করা হয়েছে ',
    'prayer_time_calibration_caps': 'নামাজের সময় ক্যালিব্রেশন',
    'no_location_set':         'কোনো অবস্থান নির্ধারণ করা হয়নি',
    'using_london_fallback':   'লন্ডন ডিফল্ট ব্যবহার করা হচ্ছে',
    'active_label':            'সক্রিয়',
    'default_label':           'ডিফল্ট',
    'gps_caps':                'GPS',
    'use_current_location':    'বর্তমান অবস্থান ব্যবহার করুন',
    'detects_city_via_gps':    'GPS দিয়ে আপনার শহর শনাক্ত করে',
    'search_city_caps':        'শহর খুঁজুন',
    'search_for_city_hint':    'একটি শহর খুঁজুন...',
    'popular_cities_caps':     'জনপ্রিয় শহর',
    'prayer_method_saved':     'নামাজ পদ্ধতি সংরক্ষিত হয়েছে।',
    'calculation_madhab_caps': 'হিসাব ও মাযহাব',
    'current_prefix':          'বর্তমান: ',
    'affects_asr_twilight':    'এটি আপনার এলাকার আসরের সময় এবং গোধূলি হিসাবকে প্রভাবিত করে।',
    'asr_madhab_caps':         'আসর মাযহাব',
    'earlier_asr':             'আগে আসর',
    'later_asr':               'পরে আসর',
    'save_prayer_method':      'নামাজ পদ্ধতি সংরক্ষণ করুন',
    'text_size_small':         'ছোট',
    'text_size_default':       'ডিফল্ট',
    'text_size_large':         'বড়',
    'text_size_extra_large':   'অতিরিক্ত বড়',
    'theme_display_caps':      'থিম ও ডিসপ্লে',
    'theme_mode_caps':         'থিম মোড',
    'use_system_default':      'সিস্টেম ডিফল্ট ব্যবহার করুন',
    'match_device_appearance': 'ডিভাইসের চেহারার সাথে মেলান',
    'text_size_caps':          'টেক্সট সাইজ',
    'profile_updated_success': 'প্রোফাইল সফলভাবে আপডেট হয়েছে',
    'profile_update_failed':   'প্রোফাইল আপডেট করতে ব্যর্থ',
    'change_password':         'পাসওয়ার্ড পরিবর্তন করুন',
    'send_reset_link_to_prefix': 'পাসওয়ার্ড রিসেট লিঙ্ক পাঠান ',
    'send_link':               'লিঙ্ক পাঠান',
    'reset_link_sent_to_prefix': 'রিসেট লিঙ্ক পাঠানো হয়েছে ',
    'failed_send_reset_link':  'রিসেট লিঙ্ক পাঠাতে ব্যর্থ',
    'personal_information_caps': 'ব্যক্তিগত তথ্য',
    'guest_label':             'অতিথি',
    'personal_details_caps':   'ব্যক্তিগত বিবরণ',
    'security_caps':           'নিরাপত্তা',
    'no_email_on_account':     'এই অ্যাকাউন্টে কোনো ইমেইল নেই',
    'danger_zone_caps':        'বিপজ্জনক অঞ্চল',
    'delete_account':          'অ্যাকাউন্ট মুছুন',
    'delete_account_confirm_body': 'আপনি কি নিশ্চিতভাবে আপনার অ্যাকাউন্ট স্থায়ীভাবে মুছে ফেলতে চান? এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।',
    'delete':                  'মুছুন',
    'share_msg_body':          'সুন্নাহ গ্র্যান্ডারে আমার সাথে যোগ দিন — আপনার ইসলামিক জীবনযাত্রার সঙ্গী!',
    'could_not_open_app':      'সেই অ্যাপটি খোলা যায়নি।',
    'share_sunnah_grandeur_caps': 'সুন্নাহ গ্র্যান্ডার শেয়ার করুন',
    'spread_the_khair':        'কল্যাণ ছড়িয়ে দিন',
    'spread_khair_body':       'সুন্নাহ গ্র্যান্ডার বন্ধু ও পরিবারের সাথে শেয়ার করুন। প্রতিটি ভালো কাজ একটি রিমাইন্ডার দিয়ে শুরু হয়।',
    'your_invite_link_caps':   'আপনার আমন্ত্রণ লিঙ্ক',
    'link_copied':             'লিঙ্ক কপি হয়েছে!',
    'share_via_caps':          'যেভাবে শেয়ার করবেন',
    'sunnah_grandeur_app_label': 'সুন্নাহ গ্র্যান্ডার অ্যাপ',
    'share_app_link':          'অ্যাপ লিঙ্ক শেয়ার করুন',
    'tap_star_first':          'প্রথমে একটি রেটিং বেছে নিতে তারকায় ট্যাপ করুন।',
    'could_not_submit_feedback': 'মতামত জমা দেওয়া যায়নি',
    'spread_the_khair_caps':   'কল্যাণ ছড়িয়ে দিন',
    'enjoying_the_app':        'অ্যাপটি উপভোগ করছেন?',
    'rating_helps_discover':   'আপনার রেটিং অন্য মুসলিমদের সুন্নাহ গ্র্যান্ডার খুঁজে পেতে সাহায্য করে। এটি মাত্র ১০ সেকেন্ড সময় নেয়।',
    'rate_app_hint':           'সুন্নাহ গ্র্যান্ডার সম্পর্কে আপনি সবচেয়ে বেশি কী পছন্দ করেন? (ঐচ্ছিক)',
    'feedback_sent':           'মতামত পাঠানো হয়েছে',
    'submit_feedback':         'মতামত জমা দিন',
    'jazakallah_khair':        'আপনার মতামতের জন্য জাযাকাল্লাহ খাইর 🤍',
    'feedback_goes_to_team':   'আপনার মতামত সরাসরি আমাদের দলের কাছে পৌঁছায়।',
  },
};

class LanguageProvider extends ChangeNotifier {
  static const _key = 'selected_locale';

  String _langCode = 'en';

  String get langCode => _langCode;
  Locale get locale   => Locale(_langCode);
  bool   get isRtl    => _langCode == 'ar';

  LanguageProvider() {
    _loadSaved();
  }

  Future<void> _loadSaved() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString(_key) ?? 'en';
    _langCode = _supported.contains(saved) ? saved : 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String code) async {
    if (!_supported.contains(code)) return;
    if (_langCode == code) return;
    _langCode = code;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_key, code);
    notifyListeners();
  }

  String tr(String key) {
    return _translations[_langCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }
}
