import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _supported = ['en', 'ar', 'bn'];

const _translations = <String, Map<String, String>>{
  // ─────────────────────────────────────────────────────────── ENGLISH ──
  'en': {
    // Global / nav
    'app_name':        'Sunnah Grandeur',
    'tagline':         'Living the Prophetic Way',
    'muslim_productivity_tag': 'Muslim Productivity, by Sunnah Grandeur',
    'home':            'Home',
    'media':           'Media',
    'store':           'Store',
    'profile':         'Profile',
    'language':        'Language',
    'location':        'Location',
    'settings':        'Settings',
    'apply':           'Apply',
    'continue':        'Continue',
    'skip':            'Skip for now',
    'save':            'Save',
    'cancel':          'Cancel',
    'done':            'Done',
    'search':          'Search',
    'back':            'Back',
    'close':           'Close',
    'loading':         'Loading...',
    'error':           'Something went wrong',
    'retry':           'Retry',
    'in':              'in',
    // Language onboarding
    'select_lang':     'Choose Your Language',
    'select_lang_sub': 'Select your preferred language\nto begin your journey',
    'continue_with':   'Continue with',
    // Home screen
    'daily_inspiration': 'Daily Inspiration',
    'hadith':            'Hadith',
    'sawm':              'Sawm',
    'active':            'Active',
    'quick_access':      'Quick Access',
    'next_prayer':       'Next Prayer',
    'namaz_schedule':    'Namaz Schedule',
    'five_prayer_times': '5 prayer times',
    'forbidden_times':   'Forbidden Times',
    'makrooh_windows':   'Makrooh windows',
    'qibla_finder':      'Qibla Finder',
    'live_compass':      'Live Compass',
    'tasbeeh':           'Tasbeeh',
    'digital_dhikr':     'Digital dhikr',
    'masjid_finder':     'Masjid Finder',
    'mosques_nearby':    'Find mosques near you',
    'zakat_calculator':  'Zakat Calculator',
    'calculate_zakat_due': 'Calculate what you owe',
    'hijri_calendar':    'Hijri Calendar',
    'islamic_lunar_dates': 'Islamic lunar dates',
    'i_fasted_today':    'I fasted today',
    'sehri':             'Sehri',
    'iftar':             'Iftar',
    'today':             'Today',
    'added_today':       'Added today',
    'calculation':       'Calculation',
    // Prayer times
    'prayer_times':    'Prayer Times',
    'fajr':            'Fajr',
    'dhuhr':           'Dhuhr',
    'asr':             'Asr',
    'maghrib':         'Maghrib',
    'isha':            'Isha',
    'sunrise':         'Sunrise',
    'sunset':          'Sunset',
    'all_prayers':     'All Prayer Times',
    // Profile screen
    'your_islamic_journey': 'Your Islamic Journey',
    'preferences':          'Preferences',
    'community':            'Community',
    'account_identity':     'Account & Identity',
    'account_sub':          'Name · Email · Password',
    'notifications':        'Notifications',
    'notifications_sub':    'Prayer alerts · Reminders',
    'appearance':           'Appearance',
    'dark_mode':            'Dark Mode',
    'light_mode':           'Light Mode',
    'prayer_method':        'Prayer Method',
    'prayer_method_sub':    'ISNA · Shafi\'i',
    'invite_friends':       'Invite Friends',
    'invite_friends_sub':   'Share Sunnah Grandeur',
    'rate_app':             'Rate the App',
    'rate_app_sub':         'Spread the khair',
    'support_us':           'Support Us',
    'support_us_sub':       'Shop with us or share the app',
    'sign_out':             'Sign Out',
    'pro_member':           'Pro Member',
    'prayers_stat':         'Prayers',
    'streak':               'Streak',
    'days_fasted':          'Days Fasted',
    'tasbeeh_stat':         'Tasbeeh',
    'guest_user':           'Guest User',
    'anonymous_account':    'Anonymous Account',
    'verified_member':      'Verified Member',
    'language_english':     'English',
    'location_default':     'Set Location',
    // Media screen
    'islamic_content_library': 'Islamic Content Library',
    'choose_section':          'Choose a Section',
    'islamic_videos':          'Islamic Videos',
    'islamic_videos_sub':      'Lectures · Tafseer · Education · Nasheeds',
    'quran':                   'Quran',
    'quran_sub':               'Tilawah · Tajweed · Memorization · Tafseer',
    'ruqyah':                  'Ruqyah',
    'ruqyah_sub':              'Healing Recitations · Protection · Evil Eye',
    'trending_now':            'Trending Now',
    'section_01':              'Section 01',
    'section_02':              'Section 02',
    'section_03':              'Section 03',
    'videos':                  'videos',
    'surahs':                  'surahs',
    'recitations':             'recitations',
    // Store screen
    'islamic_lifestyle':       'Islamic Lifestyle Essentials',
    'featured_products':       'Featured Products',
    'ramadan_exclusive':       'Ramadan Exclusive',
    'free_shipping':           'Free Shipping on £30+',
    'shop_now':                'Shop Now',
    'cat_all':                 'All',
    'cat_books':               'Books',
    'cat_clothing':            'Clothing',
    'cat_prayer':              'Prayer',
    'cat_home':                'Home',
    'cat_jewellery':           'Jewellery',
    // Auth screens
    'welcome_back':            'Welcome Back',
    'login_subtitle':          'Log in to continue your journey',
    'email':                   'Email',
    'password':                'Password',
    'forgot_password':         'Forgot Password?',
    'login':                   'Login',
    'no_account':              "Don't have an account? ",
    'register_now':            'Register Now',
    'fill_fields':             'Please fill all fields',
    'login_failed':            'Login failed. Please check your credentials.',
    'create_account':          'Create Account',
    'register_subtitle':       'Begin your Islamic journey today',
    'name':                    'Full Name',
    'register':                'Register',
    'already_account':         'Already have an account? ',
    'sign_in':                 'Sign In',
    'register_failed':         'Registration failed. Please try again.',
    'email_required':          'Email is required',
    'email_invalid':           'Enter a valid email',
    'password_required':       'Password is required',
    'save_progress':           'Save Your Progress',
    'guest_register_sub':      'Create an account to sync your favorites, orders & settings.',
    'join_community_sub':      'Join the community. Takes less than a minute.',
    'guest_session_notice':    'Your guest session will be preserved when you upgrade.',
    'continue_with_google':    'Continue with Google',
    'or_create_with_email':    'or create with email',
    'name_required':           'Name is required',
    'name_too_short':          'Name is too short',
    'min_6_chars':             'Minimum 6 characters',
    'save_upgrade_account':    'Save & Upgrade Account',
    'enter_email_prompt':      'Please enter your email',
    'reset_password_title':    'Reset Password',
    'reset_password_sub':      'Enter your email to receive a password reset link',
    'send_reset_link':         'Send Reset Link',
    'reset_link_sent':         'Password reset link sent to your email',
    'reset_link_failed':       'Failed to send reset link. Please try again.',
    // Zakat calculator
    'zakat_calc_tag':          'CALCULATE YOUR ANNUAL ZAKAT',
    'about_zakat':             'About Zakat',
    'about_zakat_body':        'Zakat is due once your total zakatable wealth has met or exceeded the Nisab '
        '(the value of 85g of gold) and has been held for one lunar year. Enter your '
        'assets below to see what you owe.',
    'your_zakatable_assets':   'YOUR ZAKATABLE ASSETS',
    'cash_savings':            'Cash & Savings',
    'cash_savings_hint':       'Bank balances, cash on hand',
    'gold_owned':              'Gold You Own (grams)',
    'gold_owned_hint':         'Total weight of gold owned',
    'silver_owned':            'Silver You Own (grams)',
    'silver_owned_hint':       'Total weight of silver owned',
    'business_assets':         'Business Assets / Inventory',
    'business_assets_hint':    'Value of stock-in-trade & receivables',
    'other_investments':       'Other Investments',
    'other_investments_hint':  'Stocks, crypto, other zakatable holdings',
    'current_market_prices':   'CURRENT MARKET PRICES',
    'live_price_refresh':      'Live price — tap to refresh',
    'tap_fetch_price':         'Tap to fetch today\'s price',
    'gold_price_gram':         'Gold Price (per gram)',
    'gold_price_gram_hint':    'Used for gold value & Nisab threshold',
    'silver_price_gram':       'Silver Price (per gram)',
    'silver_price_gram_hint':  'Used for silver value',
    'zakat_result':            'RESULT',
    'total_zakatable_wealth':  'TOTAL ZAKATABLE WEALTH',
    'gold_silver_value':       'Gold + Silver value',
    'nisab_threshold':         'NISAB THRESHOLD (85g GOLD)',
    'zakat_due_this_year':     'Zakat is due this year',
    'zakat_due_pct':           'ZAKAT DUE (2.5%)',
    'below_nisab_notice':      'Your total wealth is below the Nisab threshold — no Zakat is due this year.',
    // Onboarding
    'enable_notifications':    'Enable Notifications',
    'notifications_desc':      'Get prayer time alerts and Islamic reminders',
    'enable_btn':              'Enable',
    'maybe_later':             'Maybe Later',
    'set_location':            'Set Your Location',
    'location_desc':           'For accurate prayer times and Qibla direction',
    'detect_location':         'Detect My Location',
    // Settings
    'interface_language':      'INTERFACE LANGUAGE',
    'select_language':         'Select Language',
    'language_updated':        'Language updated',
    // Prayer tools
    'qibla':                   'Qibla',
    'qibla_sub':               'Direction to Makkah',
    'tasbeeh_counter':         'Tasbeeh Counter',
    'reset':                   'Reset',
    'forbidden_title':         'Forbidden Prayer Times',
    'nearby_masjids':          'Nearby Masjids',
    // Notifications
    'prayer_alerts':           'Prayer Alerts',
    'daily_reminder':          'Daily Reminder',
    'enabled':                 'Enabled',
    'disabled':                'Disabled',
    // Misc
    'share':                   'Share',
    'add_to_cart':             'Add to Cart',
    'checkout':                'Checkout',
    'order_confirmed':         'Order Confirmed',
    'continue_shopping':       'Continue Shopping',
    // Cart / Checkout screens
    'cart':                    'Cart',
    'your_cart':               'Your Cart',
    'cart_empty_title':        'Your cart is empty',
    'cart_empty_sub':          'Add items from the shop to get started.',
    'cart_review_sub':         'Review your selections before completing your purchase.',
    'order_summary':           'Order Summary',
    'subtotal':                'Subtotal',
    'estimated_tax':           'Estimated Tax',
    'shipping':                'Shipping',
    'free_shipping_usa':       'Free — Across the USA',
    'total':                   'Total',
    'proceed_checkout':        'PROCEED TO CHECKOUT',
    'secure_checkout':         'Secure Encrypted Checkout',
    'secure_checkout_title':   'Secure Checkout',
    'contact_information':     'Contact Information',
    'full_name':               'Full Name',
    'email_address':           'Email Address',
    'phone_number':            'Phone Number',
    'phone_required':          'Phone number is required',
    'shipping_address':        'Shipping Address',
    'street_address':          'Street Address',
    'address_required':        'Address is required',
    'city':                    'City',
    'city_required':           'City is required',
    'state_label':             'State',
    'zip_postal_code':         'ZIP / Postal Code',
    'zip_required':            'ZIP required',
    'payment_method':          'Payment Method',
    'cash_on_delivery':        'Cash on Delivery',
    'country_label':           'Country',
    'free_shipping_included':  'Free Shipping Included',
    'powered_by_stripe':       'Powered by Stripe',
    'place_order_cod':         'PLACE ORDER — PAY ON DELIVERY',
    'complete_order':          'COMPLETE ORDER',
    'subtotal_plus':           'Subtotal +',
    'tax_suffix':              'Tax',
    'ssl_encryption':          '256-bit SSL Encryption',
    'your_items':              'Your Items',
    'visit_store':             'Visit the Sunnah Grandeur Store',
    'limited_time_deal':       'Limited time deal',
    'buy_new':                 'Buy New',
    'free_shipping_prefix':    'FREE ',
    'free_shipping_line':      'shipping on every purchase',
    'free_delivery_usa':       'Free Delivery Across the USA',
    'currently_unavailable':   'Currently Unavailable',
    'in_stock':                'In Stock',
    'quantity_label':          'Quantity:',
    'add_to_cart_caps':        'ADD TO CART',
    'buy_now_caps':            'BUY NOW',
    'gift_wrap_prefix':        'Add premium gift wrapping for ',
    'delivery_support':        'DELIVERY & SUPPORT',
    'select_to_learn_more':    'Select to learn more',
    'ships_from':              'Ships from',
    'out_of_stock_caps':       'OUT OF STOCK',
    'free_delivery':           'Free Delivery',
    'across_usa':              'Across the USA',
    'returns_30day':           '30-day Easy',
    'returns':                 'Returns',
    'customer':                'Customer',
    'support':                 'Support',
    'browse':                  'BROWSE',
    'no_products_category':    'No products in this category yet.',
    'view_all_products':       'View all products',
    'categories_caps':         'CATEGORIES',
  },

  // ─────────────────────────────────────────────────────────── ARABIC ──
  'ar': {
    // Global / nav
    'app_name':        'سنة الفخامة',
    'tagline':         'العيش على الطريقة النبوية',
    'muslim_productivity_tag': 'إنتاجية المسلم، من سنة الفخامة',
    'home':            'الرئيسية',
    'media':           'الوسائط',
    'store':           'المتجر',
    'profile':         'الملف',
    'language':        'اللغة',
    'location':        'الموقع',
    'settings':        'الإعدادات',
    'apply':           'تطبيق',
    'continue':        'متابعة',
    'skip':            'تخطي',
    'save':            'حفظ',
    'cancel':          'إلغاء',
    'done':            'تم',
    'search':          'بحث',
    'back':            'رجوع',
    'close':           'إغلاق',
    'loading':         'جاري التحميل...',
    'error':           'حدث خطأ ما',
    'retry':           'إعادة المحاولة',
    'in':              'خلال',
    // Language onboarding
    'select_lang':     'اختر لغتك',
    'select_lang_sub': 'اختر لغتك المفضلة\nلبدء رحلتك',
    'continue_with':   'متابعة بـ',
    // Home screen
    'daily_inspiration': 'الإلهام اليومي',
    'hadith':            'حديث',
    'sawm':              'الصوم',
    'active':            'نشط',
    'quick_access':      'وصول سريع',
    'next_prayer':       'الصلاة القادمة',
    'namaz_schedule':    'جدول الصلاة',
    'five_prayer_times': '٥ أوقات صلاة',
    'forbidden_times':   'الأوقات المنهي عنها',
    'makrooh_windows':   'أوقات الكراهة',
    'qibla_finder':      'محدد القبلة',
    'live_compass':      'البوصلة الحية',
    'tasbeeh':           'التسبيح',
    'digital_dhikr':     'الذكر الرقمي',
    'masjid_finder':     'البحث عن مسجد',
    'mosques_nearby':    'ابحث عن المساجد القريبة منك',
    'zakat_calculator':  'حاسبة الزكاة',
    'calculate_zakat_due': 'احسب ما يجب عليك',
    'hijri_calendar':    'التقويم الهجري',
    'islamic_lunar_dates': 'التواريخ الهجرية',
    'i_fasted_today':    'صمت اليوم',
    'sehri':             'سحور',
    'iftar':             'إفطار',
    'today':             'اليوم',
    'added_today':       'أضيف اليوم',
    'calculation':       'الحساب',
    // Prayer times
    'prayer_times':    'أوقات الصلاة',
    'fajr':            'الفجر',
    'dhuhr':           'الظهر',
    'asr':             'العصر',
    'maghrib':         'المغرب',
    'isha':            'العشاء',
    'sunrise':         'الشروق',
    'sunset':          'الغروب',
    'all_prayers':     'جميع أوقات الصلاة',
    // Profile screen
    'your_islamic_journey': 'رحلتك الإسلامية',
    'preferences':          'التفضيلات',
    'community':            'المجتمع',
    'account_identity':     'الحساب والهوية',
    'account_sub':          'الاسم · البريد الإلكتروني · كلمة المرور',
    'notifications':        'الإشعارات',
    'notifications_sub':    'تنبيهات الصلاة · التذكيرات',
    'appearance':           'المظهر',
    'dark_mode':            'الوضع الداكن',
    'light_mode':           'الوضع الفاتح',
    'prayer_method':        'طريقة حساب الصلاة',
    'prayer_method_sub':    'رابطة الإسلام الشمالية · شافعي',
    'invite_friends':       'دعوة الأصدقاء',
    'invite_friends_sub':   'شارك سنة الفخامة',
    'rate_app':             'تقييم التطبيق',
    'rate_app_sub':         'انشر الخير',
    'support_us':           'ادعمنا',
    'support_us_sub':       'تسوق معنا أو شارك التطبيق',
    'sign_out':             'تسجيل الخروج',
    'pro_member':           'عضو مميز',
    'prayers_stat':         'صلوات',
    'streak':               'تسلسل',
    'days_fasted':          'أيام الصيام',
    'tasbeeh_stat':         'تسبيح',
    'guest_user':           'مستخدم ضيف',
    'anonymous_account':    'حساب مجهول',
    'verified_member':      'عضو موثق',
    'language_english':     'اللغة',
    'location_default':     'تحديد الموقع',
    // Media screen
    'islamic_content_library': 'مكتبة المحتوى الإسلامي',
    'choose_section':          'اختر قسماً',
    'islamic_videos':          'الفيديوهات الإسلامية',
    'islamic_videos_sub':      'المحاضرات · التفسير · التعليم · الأناشيد',
    'quran':                   'القرآن',
    'quran_sub':               'التلاوة · التجويد · الحفظ · التفسير',
    'ruqyah':                  'الرقية',
    'ruqyah_sub':              'تلاوات شفائية · الحماية · العين',
    'trending_now':            'الأكثر انتشاراً',
    'section_01':              'القسم ٠١',
    'section_02':              'القسم ٠٢',
    'section_03':              'القسم ٠٣',
    'videos':                  'فيديو',
    'surahs':                  'سور',
    'recitations':             'تلاوة',
    // Store screen
    'islamic_lifestyle':       'مستلزمات نمط الحياة الإسلامية',
    'featured_products':       'المنتجات المميزة',
    'ramadan_exclusive':       'إصدار رمضاني',
    'free_shipping':           'شحن مجاني عند ٣٠ جنيه+',
    'shop_now':                'تسوق الآن',
    'cat_all':                 'الكل',
    'cat_books':               'الكتب',
    'cat_clothing':            'الملابس',
    'cat_prayer':              'الصلاة',
    'cat_home':                'المنزل',
    'cat_jewellery':           'المجوهرات',
    // Auth screens
    'welcome_back':            'مرحباً بعودتك',
    'login_subtitle':          'سجّل دخولك لمتابعة رحلتك',
    'email':                   'البريد الإلكتروني',
    'password':                'كلمة المرور',
    'forgot_password':         'نسيت كلمة المرور؟',
    'login':                   'تسجيل الدخول',
    'no_account':              'ليس لديك حساب؟ ',
    'register_now':            'سجّل الآن',
    'fill_fields':             'يرجى ملء جميع الحقول',
    'login_failed':            'فشل تسجيل الدخول. يرجى التحقق من بيانات الاعتماد.',
    'create_account':          'إنشاء حساب',
    'register_subtitle':       'ابدأ رحلتك الإسلامية اليوم',
    'name':                    'الاسم الكامل',
    'register':                'تسجيل',
    'already_account':         'لديك حساب بالفعل؟ ',
    'sign_in':                 'تسجيل الدخول',
    'register_failed':         'فشل التسجيل. يرجى المحاولة مرة أخرى.',
    'email_required':          'البريد الإلكتروني مطلوب',
    'email_invalid':           'أدخل بريدًا إلكترونيًا صحيحًا',
    'password_required':       'كلمة المرور مطلوبة',
    'save_progress':           'احفظ تقدمك',
    'guest_register_sub':      'أنشئ حسابًا لمزامنة المفضلة والطلبات والإعدادات.',
    'join_community_sub':      'انضم إلى المجتمع. يستغرق أقل من دقيقة.',
    'guest_session_notice':    'سيتم الحفاظ على جلستك كضيف عند الترقية.',
    'continue_with_google':    'المتابعة عبر جوجل',
    'or_create_with_email':    'أو أنشئ حسابًا بالبريد الإلكتروني',
    'name_required':           'الاسم مطلوب',
    'name_too_short':          'الاسم قصير جدًا',
    'min_6_chars':             'الحد الأدنى 6 أحرف',
    'save_upgrade_account':    'حفظ وترقية الحساب',
    'enter_email_prompt':      'يرجى إدخال بريدك الإلكتروني',
    'reset_password_title':    'إعادة تعيين كلمة المرور',
    'reset_password_sub':      'أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور',
    'send_reset_link':         'إرسال رابط إعادة التعيين',
    'reset_link_sent':         'تم إرسال رابط إعادة التعيين إلى بريدك الإلكتروني',
    'reset_link_failed':       'فشل إرسال الرابط. يرجى المحاولة مرة أخرى.',
    // Zakat calculator
    'zakat_calc_tag':          'احسب زكاتك السنوية',
    'about_zakat':             'عن الزكاة',
    'about_zakat_body':        'تجب الزكاة عندما تبلغ ثروتك الخاضعة للزكاة النصاب '
        '(قيمة 85 غرامًا من الذهب) وتحول عليها الحول. أدخل '
        'أصولك أدناه لمعرفة المبلغ المستحق.',
    'your_zakatable_assets':   'أصولك الخاضعة للزكاة',
    'cash_savings':            'النقد والمدخرات',
    'cash_savings_hint':       'أرصدة البنك والنقد المتوفر',
    'gold_owned':              'الذهب الذي تملكه (غرام)',
    'gold_owned_hint':         'إجمالي وزن الذهب المملوك',
    'silver_owned':            'الفضة التي تملكها (غرام)',
    'silver_owned_hint':       'إجمالي وزن الفضة المملوكة',
    'business_assets':         'أصول العمل / المخزون',
    'business_assets_hint':    'قيمة المخزون والذمم المدينة',
    'other_investments':       'استثمارات أخرى',
    'other_investments_hint':  'الأسهم والعملات الرقمية وغيرها من الممتلكات الخاضعة للزكاة',
    'current_market_prices':   'أسعار السوق الحالية',
    'live_price_refresh':      'سعر مباشر — اضغط للتحديث',
    'tap_fetch_price':         'اضغط لجلب سعر اليوم',
    'gold_price_gram':         'سعر الذهب (لكل غرام)',
    'gold_price_gram_hint':    'يُستخدم لقيمة الذهب وحد النصاب',
    'silver_price_gram':       'سعر الفضة (لكل غرام)',
    'silver_price_gram_hint':  'يُستخدم لقيمة الفضة',
    'zakat_result':            'النتيجة',
    'total_zakatable_wealth':  'إجمالي الثروة الخاضعة للزكاة',
    'gold_silver_value':       'قيمة الذهب والفضة',
    'nisab_threshold':         'حد النصاب (85 غرام ذهب)',
    'zakat_due_this_year':     'الزكاة مستحقة هذا العام',
    'zakat_due_pct':           'الزكاة المستحقة (2.5%)',
    'below_nisab_notice':      'ثروتك الإجمالية أقل من حد النصاب — لا زكاة مستحقة هذا العام.',
    // Onboarding
    'enable_notifications':    'تفعيل الإشعارات',
    'notifications_desc':      'احصل على تنبيهات أوقات الصلاة وتذكيرات إسلامية',
    'enable_btn':              'تفعيل',
    'maybe_later':             'ربما لاحقاً',
    'set_location':            'تحديد موقعك',
    'location_desc':           'لأوقات صلاة دقيقة واتجاه القبلة',
    'detect_location':         'تحديد موقعي',
    // Settings
    'interface_language':      'لغة الواجهة',
    'select_language':         'اختر اللغة',
    'language_updated':        'تم تحديث اللغة',
    // Prayer tools
    'qibla':                   'القبلة',
    'qibla_sub':               'اتجاه مكة المكرمة',
    'tasbeeh_counter':         'عداد التسبيح',
    'reset':                   'إعادة ضبط',
    'forbidden_title':         'أوقات الصلاة المنهي عنها',
    'nearby_masjids':          'المساجد القريبة',
    // Notifications
    'prayer_alerts':           'تنبيهات الصلاة',
    'daily_reminder':          'التذكير اليومي',
    'enabled':                 'مفعّل',
    'disabled':                'معطّل',
    // Misc
    'share':                   'مشاركة',
    'add_to_cart':             'أضف إلى السلة',
    'checkout':                'الدفع',
    'order_confirmed':         'تم تأكيد الطلب',
    'continue_shopping':       'متابعة التسوق',
    'cart':                    'السلة',
    'your_cart':               'سلتك',
    'cart_empty_title':        'سلتك فارغة',
    'cart_empty_sub':          'أضف منتجات من المتجر للبدء.',
    'cart_review_sub':         'راجع اختياراتك قبل إتمام الشراء.',
    'order_summary':           'ملخص الطلب',
    'subtotal':                'المجموع الفرعي',
    'estimated_tax':           'الضريبة المقدرة',
    'shipping':                'الشحن',
    'free_shipping_usa':       'مجاني — في جميع أنحاء الولايات المتحدة',
    'total':                   'الإجمالي',
    'proceed_checkout':        'المتابعة إلى الدفع',
    'secure_checkout':         'دفع آمن ومشفر',
    'secure_checkout_title':   'الدفع الآمن',
    'contact_information':     'معلومات الاتصال',
    'full_name':               'الاسم الكامل',
    'email_address':           'البريد الإلكتروني',
    'phone_number':            'رقم الهاتف',
    'phone_required':          'رقم الهاتف مطلوب',
    'shipping_address':        'عنوان الشحن',
    'street_address':          'عنوان الشارع',
    'address_required':        'العنوان مطلوب',
    'city':                    'المدينة',
    'city_required':           'المدينة مطلوبة',
    'state_label':             'الولاية',
    'zip_postal_code':         'الرمز البريدي',
    'zip_required':            'الرمز البريدي مطلوب',
    'payment_method':          'طريقة الدفع',
    'cash_on_delivery':        'الدفع عند الاستلام',
    'country_label':           'البلد',
    'free_shipping_included':  'شحن مجاني',
    'powered_by_stripe':       'مدعوم بواسطة Stripe',
    'place_order_cod':         'تأكيد الطلب — الدفع عند الاستلام',
    'complete_order':          'إتمام الطلب',
    'subtotal_plus':           'المجموع الفرعي +',
    'tax_suffix':              'ضريبة',
    'ssl_encryption':          'تشفير SSL 256-بت',
    'your_items':              'مشترياتك',
    'visit_store':             'زيارة متجر سنة الفخامة',
    'limited_time_deal':       'عرض لفترة محدودة',
    'buy_new':                 'اشترِ جديدًا',
    'free_shipping_prefix':    'مجاني ',
    'free_shipping_line':      'شحن مجاني على كل عملية شراء',
    'free_delivery_usa':       'توصيل مجاني في جميع أنحاء الولايات المتحدة',
    'currently_unavailable':   'غير متوفر حاليًا',
    'in_stock':                'متوفر',
    'quantity_label':          'الكمية:',
    'add_to_cart_caps':        'أضف إلى السلة',
    'buy_now_caps':            'اشترِ الآن',
    'gift_wrap_prefix':        'أضف تغليف هدية فاخر مقابل ',
    'delivery_support':        'التوصيل والدعم',
    'select_to_learn_more':    'اختر لمعرفة المزيد',
    'ships_from':              'يُشحن من',
    'out_of_stock_caps':       'نفدت الكمية',
    'free_delivery':           'توصيل مجاني',
    'across_usa':              'في جميع أنحاء الولايات المتحدة',
    'returns_30day':           'إرجاع سهل',
    'returns':                 'خلال 30 يومًا',
    'customer':                'خدمة',
    'support':                 'العملاء',
    'browse':                  'تصفح',
    'no_products_category':    'لا توجد منتجات في هذه الفئة بعد.',
    'view_all_products':       'عرض جميع المنتجات',
    'categories_caps':         'الفئات',
  },

  // ─────────────────────────────────────────────────────────── BANGLA ──
  'bn': {
    // Global / nav
    'app_name':        'সুন্নাহ গ্র্যান্ডার',
    'tagline':         'নবীজির পথে জীবন যাপন',
    'muslim_productivity_tag': 'মুসলিম প্রোডাক্টিভিটি, সুন্নাহ গ্র্যান্ডার থেকে',
    'home':            'হোম',
    'media':           'মিডিয়া',
    'store':           'স্টোর',
    'profile':         'প্রোফাইল',
    'language':        'ভাষা',
    'location':        'অবস্থান',
    'settings':        'সেটিংস',
    'apply':           'প্রয়োগ করুন',
    'continue':        'চালিয়ে যান',
    'skip':            'এখন এড়িয়ে যান',
    'save':            'সংরক্ষণ',
    'cancel':          'বাতিল',
    'done':            'সম্পন্ন',
    'search':          'অনুসন্ধান',
    'back':            'পিছনে',
    'close':           'বন্ধ',
    'loading':         'লোড হচ্ছে...',
    'error':           'কিছু একটা ভুল হয়েছে',
    'retry':           'আবার চেষ্টা করুন',
    'in':              'পরে',
    // Language onboarding
    'select_lang':     'আপনার ভাষা বেছে নিন',
    'select_lang_sub': 'আপনার পছন্দের ভাষা নির্বাচন করুন\nযাত্রা শুরু করতে',
    'continue_with':   'এগিয়ে যান',
    // Home screen
    'daily_inspiration': 'দৈনিক অনুপ্রেরণা',
    'hadith':            'হাদিস',
    'sawm':              'সাওম',
    'active':            'সক্রিয়',
    'quick_access':      'দ্রুত অ্যাক্সেস',
    'next_prayer':       'পরবর্তী নামাজ',
    'namaz_schedule':    'নামাজের সময়সূচি',
    'five_prayer_times': '৫ ওয়াক্ত নামাজ',
    'forbidden_times':   'নিষিদ্ধ সময়',
    'makrooh_windows':   'মাকরুহ সময়',
    'qibla_finder':      'কিবলা নির্ণয়',
    'live_compass':      'লাইভ কম্পাস',
    'tasbeeh':           'তাসবিহ',
    'digital_dhikr':     'ডিজিটাল জিকর',
    'masjid_finder':     'মসজিদ খুঁজুন',
    'mosques_nearby':    'আপনার কাছের মসজিদ খুঁজুন',
    'zakat_calculator':  'যাকাত ক্যালকুলেটর',
    'calculate_zakat_due': 'আপনার যাকাত হিসাব করুন',
    'hijri_calendar':    'হিজরি ক্যালেন্ডার',
    'islamic_lunar_dates': 'ইসলামিক চান্দ্র তারিখ',
    'i_fasted_today':    'আজ রোজা রেখেছি',
    'sehri':             'সেহরি',
    'iftar':             'ইফতার',
    'today':             'আজ',
    'added_today':       'আজ যোগ হয়েছে',
    'calculation':       'হিসাব',
    // Prayer times
    'prayer_times':    'নামাজের সময়',
    'fajr':            'ফজর',
    'dhuhr':           'যোহর',
    'asr':             'আসর',
    'maghrib':         'মাগরিব',
    'isha':            'এশা',
    'sunrise':         'সূর্যোদয়',
    'sunset':          'সূর্যাস্ত',
    'all_prayers':     'সব নামাজের সময়',
    // Profile screen
    'your_islamic_journey': 'আপনার ইসলামি যাত্রা',
    'preferences':          'পছন্দসমূহ',
    'community':            'সম্প্রদায়',
    'account_identity':     'অ্যাকাউন্ট ও পরিচয়',
    'account_sub':          'নাম · ইমেইল · পাসওয়ার্ড',
    'notifications':        'বিজ্ঞপ্তি',
    'notifications_sub':    'নামাজের সতর্কতা · রিমাইন্ডার',
    'appearance':           'উপস্থিতি',
    'dark_mode':            'ডার্ক মোড',
    'light_mode':           'লাইট মোড',
    'prayer_method':        'নামাজ হিসাবের পদ্ধতি',
    'prayer_method_sub':    'ISNA · শাফেয়ি',
    'invite_friends':       'বন্ধুদের আমন্ত্রণ জানান',
    'invite_friends_sub':   'সুন্নাহ গ্র্যান্ডার শেয়ার করুন',
    'rate_app':             'অ্যাপ রেটিং দিন',
    'rate_app_sub':         'কল্যাণ ছড়িয়ে দিন',
    'support_us':           'আমাদের সাহায্য করুন',
    'support_us_sub':       'আমাদের থেকে কিনুন অথবা অ্যাপটি শেয়ার করুন',
    'sign_out':             'সাইন আউট',
    'pro_member':           'প্রো সদস্য',
    'prayers_stat':         'নামাজ',
    'streak':               'ধারাবাহিকতা',
    'days_fasted':          'রোজার দিন',
    'tasbeeh_stat':         'তাসবিহ',
    'guest_user':           'অতিথি ব্যবহারকারী',
    'anonymous_account':    'বেনামী অ্যাকাউন্ট',
    'verified_member':      'যাচাইকৃত সদস্য',
    'language_english':     'ভাষা',
    'location_default':     'অবস্থান নির্ধারণ করুন',
    // Media screen
    'islamic_content_library': 'ইসলামিক কন্টেন্ট লাইব্রেরি',
    'choose_section':          'একটি বিভাগ বেছে নিন',
    'islamic_videos':          'ইসলামিক ভিডিও',
    'islamic_videos_sub':      'বক্তৃতা · তাফসির · শিক্ষা · নাশিদ',
    'quran':                   'কুরআন',
    'quran_sub':               'তিলাওয়াত · তাজওয়িদ · হিফজ · তাফসির',
    'ruqyah':                  'রুকইয়াহ',
    'ruqyah_sub':              'নিরাময় তিলাওয়াত · সুরক্ষা · নজর',
    'trending_now':            'এখন ট্রেন্ডিং',
    'section_01':              'বিভাগ ০১',
    'section_02':              'বিভাগ ০২',
    'section_03':              'বিভাগ ০৩',
    'videos':                  'ভিডিও',
    'surahs':                  'সূরা',
    'recitations':             'তিলাওয়াত',
    // Store screen
    'islamic_lifestyle':       'ইসলামিক জীবনযাত্রার পণ্য',
    'featured_products':       'বৈশিষ্ট্যযুক্ত পণ্য',
    'ramadan_exclusive':       'রমজান এক্সক্লুসিভ',
    'free_shipping':           '£৩০+ এ বিনামূল্যে শিপিং',
    'shop_now':                'এখন কিনুন',
    'cat_all':                 'সব',
    'cat_books':               'বই',
    'cat_clothing':            'পোশাক',
    'cat_prayer':              'নামাজ',
    'cat_home':                'গৃহ',
    'cat_jewellery':           'গহনা',
    // Auth screens
    'welcome_back':            'আবার স্বাগতম',
    'login_subtitle':          'আপনার যাত্রা চালিয়ে যেতে লগ ইন করুন',
    'email':                   'ইমেইল',
    'password':                'পাসওয়ার্ড',
    'forgot_password':         'পাসওয়ার্ড ভুলে গেছেন?',
    'login':                   'লগ ইন',
    'no_account':              'অ্যাকাউন্ট নেই? ',
    'register_now':            'এখনই নিবন্ধন করুন',
    'fill_fields':             'সকল ঘর পূরণ করুন',
    'login_failed':            'লগইন ব্যর্থ হয়েছে। আপনার তথ্য যাচাই করুন।',
    'create_account':          'অ্যাকাউন্ট তৈরি করুন',
    'register_subtitle':       'আজই আপনার ইসলামিক যাত্রা শুরু করুন',
    'name':                    'পূর্ণ নাম',
    'register':                'নিবন্ধন করুন',
    'already_account':         'ইতিমধ্যে অ্যাকাউন্ট আছে? ',
    'sign_in':                 'সাইন ইন',
    'register_failed':         'নিবন্ধন ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    'email_required':          'ইমেইল আবশ্যক',
    'email_invalid':           'একটি সঠিক ইমেইল দিন',
    'password_required':       'পাসওয়ার্ড আবশ্যক',
    'save_progress':           'আপনার অগ্রগতি সংরক্ষণ করুন',
    'guest_register_sub':      'আপনার পছন্দ, অর্ডার ও সেটিংস সিঙ্ক করতে একটি অ্যাকাউন্ট তৈরি করুন।',
    'join_community_sub':      'কমিউনিটিতে যোগ দিন। এক মিনিটেরও কম সময় লাগে।',
    'guest_session_notice':    'আপগ্রেড করার সময় আপনার গেস্ট সেশন সংরক্ষিত থাকবে।',
    'continue_with_google':    'গুগল দিয়ে চালিয়ে যান',
    'or_create_with_email':    'অথবা ইমেইল দিয়ে অ্যাকাউন্ট তৈরি করুন',
    'name_required':           'নাম আবশ্যক',
    'name_too_short':          'নামটি খুব ছোট',
    'min_6_chars':             'ন্যূনতম ৬ অক্ষর',
    'save_upgrade_account':    'সংরক্ষণ ও অ্যাকাউন্ট আপগ্রেড করুন',
    'enter_email_prompt':      'অনুগ্রহ করে আপনার ইমেইল দিন',
    'reset_password_title':    'পাসওয়ার্ড রিসেট করুন',
    'reset_password_sub':      'পাসওয়ার্ড রিসেট লিঙ্ক পেতে আপনার ইমেইল দিন',
    'send_reset_link':         'রিসেট লিঙ্ক পাঠান',
    'reset_link_sent':         'পাসওয়ার্ড রিসেট লিঙ্ক আপনার ইমেইলে পাঠানো হয়েছে',
    'reset_link_failed':       'লিঙ্ক পাঠাতে ব্যর্থ। আবার চেষ্টা করুন।',
    // Zakat calculator
    'zakat_calc_tag':          'আপনার বার্ষিক যাকাত হিসাব করুন',
    'about_zakat':             'যাকাত সম্পর্কে',
    'about_zakat_body':        'আপনার মোট যাকাতযোগ্য সম্পদ নিসাব '
        '(৮৫ গ্রাম স্বর্ণের মূল্য) পৌঁছালে এবং এক চন্দ্র বছর ধরে থাকলে যাকাত ফরজ হয়। '
        'আপনার প্রদেয় যাকাত জানতে নিচে সম্পদের তথ্য দিন।',
    'your_zakatable_assets':   'আপনার যাকাতযোগ্য সম্পদ',
    'cash_savings':            'নগদ ও সঞ্চয়',
    'cash_savings_hint':       'ব্যাংক ব্যালেন্স, হাতে নগদ',
    'gold_owned':              'আপনার মালিকানাধীন স্বর্ণ (গ্রাম)',
    'gold_owned_hint':         'মালিকানাধীন স্বর্ণের মোট ওজন',
    'silver_owned':            'আপনার মালিকানাধীন রূপা (গ্রাম)',
    'silver_owned_hint':       'মালিকানাধীন রূপার মোট ওজন',
    'business_assets':         'ব্যবসায়িক সম্পদ / মজুদ',
    'business_assets_hint':    'পণ্য মজুদ ও পাওনার মূল্য',
    'other_investments':       'অন্যান্য বিনিয়োগ',
    'other_investments_hint':  'শেয়ার, ক্রিপ্টো, অন্যান্য যাকাতযোগ্য সম্পদ',
    'current_market_prices':   'বর্তমান বাজার মূল্য',
    'live_price_refresh':      'লাইভ মূল্য — রিফ্রেশ করতে ট্যাপ করুন',
    'tap_fetch_price':         'আজকের মূল্য আনতে ট্যাপ করুন',
    'gold_price_gram':         'স্বর্ণের মূল্য (প্রতি গ্রাম)',
    'gold_price_gram_hint':    'স্বর্ণের মূল্য ও নিসাব নির্ধারণে ব্যবহৃত',
    'silver_price_gram':       'রূপার মূল্য (প্রতি গ্রাম)',
    'silver_price_gram_hint':  'রূপার মূল্য নির্ধারণে ব্যবহৃত',
    'zakat_result':            'ফলাফল',
    'total_zakatable_wealth':  'মোট যাকাতযোগ্য সম্পদ',
    'gold_silver_value':       'স্বর্ণ + রূপার মূল্য',
    'nisab_threshold':         'নিসাব সীমা (৮৫ গ্রাম স্বর্ণ)',
    'zakat_due_this_year':     'এই বছর যাকাত ফরজ',
    'zakat_due_pct':           'প্রদেয় যাকাত (২.৫%)',
    'below_nisab_notice':      'আপনার মোট সম্পদ নিসাব সীমার নিচে — এই বছর যাকাত ফরজ নয়।',
    // Onboarding
    'enable_notifications':    'বিজ্ঞপ্তি চালু করুন',
    'notifications_desc':      'নামাজের সময়ের সতর্কতা ও ইসলামিক রিমাইন্ডার পান',
    'enable_btn':              'চালু করুন',
    'maybe_later':             'পরে হয়তো',
    'set_location':            'আপনার অবস্থান নির্ধারণ করুন',
    'location_desc':           'সঠিক নামাজের সময় ও কিবলার দিকের জন্য',
    'detect_location':         'আমার অবস্থান শনাক্ত করুন',
    // Settings
    'interface_language':      'ইন্টারফেস ভাষা',
    'select_language':         'ভাষা নির্বাচন করুন',
    'language_updated':        'ভাষা আপডেট হয়েছে',
    // Prayer tools
    'qibla':                   'কিবলা',
    'qibla_sub':               'মক্কার দিক',
    'tasbeeh_counter':         'তাসবিহ কাউন্টার',
    'reset':                   'রিসেট',
    'forbidden_title':         'নিষিদ্ধ নামাজের সময়',
    'nearby_masjids':          'কাছের মসজিদ',
    // Notifications
    'prayer_alerts':           'নামাজের সতর্কতা',
    'daily_reminder':          'দৈনিক রিমাইন্ডার',
    'enabled':                 'সক্রিয়',
    'disabled':                'নিষ্ক্রিয়',
    // Misc
    'share':                   'শেয়ার',
    'add_to_cart':             'কার্টে যোগ করুন',
    'checkout':                'চেকআউট',
    'order_confirmed':         'অর্ডার নিশ্চিত হয়েছে',
    'continue_shopping':       'কেনাকাটা চালিয়ে যান',
    'cart':                    'কার্ট',
    'your_cart':               'আপনার কার্ট',
    'cart_empty_title':        'আপনার কার্ট খালি',
    'cart_empty_sub':          'শুরু করতে দোকান থেকে পণ্য যোগ করুন।',
    'cart_review_sub':         'কেনাকাটা সম্পূর্ণ করার আগে আপনার নির্বাচনগুলো পর্যালোচনা করুন।',
    'order_summary':           'অর্ডার সারাংশ',
    'subtotal':                'সাবটোটাল',
    'estimated_tax':           'আনুমানিক কর',
    'shipping':                'শিপিং',
    'free_shipping_usa':       'বিনামূল্যে — সারা যুক্তরাষ্ট্র জুড়ে',
    'total':                   'মোট',
    'proceed_checkout':        'চেকআউটে যান',
    'secure_checkout':         'নিরাপদ এনক্রিপ্টেড চেকআউট',
    'secure_checkout_title':   'নিরাপদ চেকআউট',
    'contact_information':     'যোগাযোগের তথ্য',
    'full_name':               'পূর্ণ নাম',
    'email_address':           'ইমেইল ঠিকানা',
    'phone_number':            'ফোন নম্বর',
    'phone_required':          'ফোন নম্বর আবশ্যক',
    'shipping_address':        'শিপিং ঠিকানা',
    'street_address':          'রাস্তার ঠিকানা',
    'address_required':        'ঠিকানা আবশ্যক',
    'city':                    'শহর',
    'city_required':           'শহর আবশ্যক',
    'state_label':             'রাজ্য',
    'zip_postal_code':         'জিপ / পোস্টাল কোড',
    'zip_required':            'জিপ কোড আবশ্যক',
    'payment_method':          'পেমেন্ট পদ্ধতি',
    'cash_on_delivery':        'ক্যাশ অন ডেলিভারি',
    'country_label':           'দেশ',
    'free_shipping_included':  'ফ্রি শিপিং অন্তর্ভুক্ত',
    'powered_by_stripe':       'Stripe দ্বারা পরিচালিত',
    'place_order_cod':         'অর্ডার করুন — ডেলিভারিতে পরিশোধ',
    'complete_order':          'অর্ডার সম্পন্ন করুন',
    'subtotal_plus':           'সাবটোটাল +',
    'tax_suffix':              'কর',
    'ssl_encryption':          '২৫৬-বিট SSL এনক্রিপশন',
    'your_items':              'আপনার আইটেম',
    'visit_store':             'সুন্নাহ গ্র্যান্ডার স্টোর দেখুন',
    'limited_time_deal':       'সীমিত সময়ের অফার',
    'buy_new':                 'নতুন কিনুন',
    'free_shipping_prefix':    'ফ্রি ',
    'free_shipping_line':      'প্রতিটি ক্রয়ে শিপিং',
    'free_delivery_usa':       'সারা যুক্তরাষ্ট্রে ফ্রি ডেলিভারি',
    'currently_unavailable':   'বর্তমানে অনুপলব্ধ',
    'in_stock':                'স্টকে আছে',
    'quantity_label':          'পরিমাণ:',
    'add_to_cart_caps':        'কার্টে যোগ করুন',
    'buy_now_caps':            'এখনই কিনুন',
    'gift_wrap_prefix':        'প্রিমিয়াম গিফট র‍্যাপিং যোগ করুন মাত্র ',
    'delivery_support':        'ডেলিভারি ও সহায়তা',
    'select_to_learn_more':    'আরও জানতে নির্বাচন করুন',
    'ships_from':              'পাঠানো হয়',
    'out_of_stock_caps':       'স্টক নেই',
    'free_delivery':           'ফ্রি ডেলিভারি',
    'across_usa':              'সারা যুক্তরাষ্ট্রে',
    'returns_30day':           '৩০-দিনের সহজ',
    'returns':                 'রিটার্ন',
    'customer':                'গ্রাহক',
    'support':                 'সহায়তা',
    'browse':                  'ব্রাউজ করুন',
    'no_products_category':    'এই ক্যাটাগরিতে এখনও কোনো পণ্য নেই।',
    'view_all_products':       'সব পণ্য দেখুন',
    'categories_caps':         'ক্যাটাগরি',
  },
};

class LanguageProvider extends ChangeNotifier {
  static const _key = 'selected_locale';

  String _langCode = 'en';

  String get langCode => _langCode;
  Locale get locale   => Locale(_langCode);
  bool   get isRtl    => _langCode == 'ar';

  LanguageProvider() {
    _loadSaved();
  }

  Future<void> _loadSaved() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString(_key) ?? 'en';
    _langCode = _supported.contains(saved) ? saved : 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String code) async {
    if (!_supported.contains(code)) return;
    if (_langCode == code) return;
    _langCode = code;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_key, code);
    notifyListeners();
  }

  String tr(String key) {
    return _translations[_langCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }
}
