// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX3H10keVelz9HppzN_Y0BKqhPWRCqV8U',
    appId: '1:6748865044:web:a50ab96d823a83bacd1d01',
    messagingSenderId: '6748865044',
    projectId: 'sunnah-grandeur',
    authDomain: 'sunnah-grandeur.firebaseapp.com',
    storageBucket: 'sunnah-grandeur.firebasestorage.app',
    measurementId: 'G-J5H9HT8TTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOW-85wwjLEp13fHLBSM1-MmZk_Sw9wuU',
    appId: '1:6748865044:android:21622fa6b98dcd59cd1d01',
    messagingSenderId: '6748865044',
    projectId: 'sunnah-grandeur',
    storageBucket: 'sunnah-grandeur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsDiuGhEpRD_9j5Qz2j9AAXoG6842R0Mg',
    appId: '1:6748865044:ios:c6cfccf8c7b7415ccd1d01',
    messagingSenderId: '6748865044',
    projectId: 'sunnah-grandeur',
    storageBucket: 'sunnah-grandeur.firebasestorage.app',
    iosBundleId: 'com.sunnahgrandeur.app',
  );
}